### ISSUE TITLE
Can't export results from Ingenuity - 2 urgent patients

### ISSUE THREAD

**Issue by helenstorey** [moka-guys/helpdesk#102]
Hi

Ingenuity will no longer let us export a text file containing the results, but it exports a zipped file.  I need the results unzipping for NGS210 Alports analysis ASAP since I have two urgent patients on there, have to leave at 3.30pm and don't work tuesdays!  The results have been exported to:
P:\DNA LAB\Current\NGS worksheets\NGS_201 to 300\NGS_210\NGS210_ALP\NGS210_ALP(NGSEQ1)_Pr.txt.gz

Many thanks
Helen

**Comment by woook** [comment]
?Done


________________________________

**Comment by helenstorey** [comment]
Thanks very much
