### ISSUE TITLE
NGS196

### ISSUE THREAD

**Issue by helenstorey** [moka-guys/helpdesk#11]
Hi
The coverage files for NGS196 seem a bit odd.  Most of them end in .refined.exon_level.txt and are fine, just as normal.  But some files end in .refined.chanjo_txt and don't appear to be correct.
I was just wondering if the correct format coverage files could be put in.

Many thanks
Helen

**Comment by aledj2** [comment]
sorry my mistake. The correct files should be there now

**Comment by helenstorey** [comment]
Thanks for sorting it so quickly!
