### ISSUE TITLE
WES - Ingenuity upload

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#111]
Hi,

Can the VCFs from the following cases be uploaded into Ingenuity, please.
148146, 194844, 193908

Run:
180309_NB551068_0108_AHLTVGBGX5_NGS201B_WES26_WES22

Cheers,  /Matt

**Comment by aledj2** [comment]
These have been shared with the wesviapath account. They should be there in the next few minutes.
Aled
