### ISSUE TITLE
WES - variant list

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#114]
Hi,

Every time I open a new patient results page, the variant list is sorted in an annoying way and I have to go in and remove the sorting. This is a recent issue and I can't figure what has happened to have 'sorted' as default when opening a case rather than 'not sorted'. Work your magic!

Cheers, /Matt

**Comment by MattiasJanssonviapath** [comment]
Sue has the same issue but with another set of sort as default...

**Comment by andyb3** [comment]
Please can you check if this is still an issue following today's update?

**Comment by MattiasJanssonviapath** [comment]
The issue seems to be gone at least when opening a case. I haven't tried importing yet.

**Comment by andyb3** [comment]
That's good. I will close the issue for now, but feel free to re-open if it returns
