### ISSUE TITLE
NGS data re-analysis needed - URGENT

### ISSUE THREAD

**Issue by jocampbell** [moka-guys/helpdesk#123]
Oxford Lab have found a reportable BRCA2 variant in a sample we have tested, we didn't detect this variant.  We need to look back at our data to see if the variant is there, and if there is a reason we might have missed it.
The Fastq files are on the Pluto hard drive.  Sample is NGS107A-14-161698-JS.
I have the pluto HD on my desk at the moment.
Please can this be put into Ingenuity so that we can re-check the data.
thanks
Jo

**Comment by AmyAmelia** [comment]
Hi Jo,
Do you know where the Nextgene vcf is? Also did you want us to run the fastq through the current pipeline?

**Comment by jocampbell** [comment]
Hi Amy,

As it is old data all we have is the fastq files and the Nextgene mutation report (which doesn’t have the variant), so the analysis will need to be done again – as we don’t have Nextgene now then I guess that means it will need to go through the current pipeline?

If you want to see the mutation report it is saved here;

P:\DNA LAB\Current\NGS worksheets\NGS_101 to 200\NGS_107\Sample Files\NGS107A_BRCA\NGS107A-14-161698-JS-BRCA2814_Output\NGS107A-14-161698-JS-BRCA2814_Mutation_Report1.txt<file:///\\gstt.local\shared\Genetics\DNA%20LAB\Current\NGS%20worksheets\NGS_101%20to%20200\NGS_107\Sample%20Files\NGS107A_BRCA\NGS107A-14-161698-JS-BRCA2814_Output\NGS107A-14-161698-JS-BRCA2814_Mutation_Report1.txt>

Thanks

Jo
Joanna Campbell PhD | Viapath
Clinical Scientist
Molecular Genetics
5th Floor Tower Wing |Guy's Hospital| London | SE1 9RT
020 7188 1714 (Tel)
020 7188 1697 (Fax)
joanna.campbell@viapath.co.uk<mailto:joanna.campbell@viapath.co.uk>
joanna.campbell3@nhs.net<mailto:joanna.campbell3@nhs.net>
A unique partnership of clinical, scientific and operational expertise, on a mission to transform pathology services in the UK.

Find out more at www.viapath.co.uk<http://viapath.us10.list-manage.com/track/click?u=650308f65b655be63608468c8&id=a65cf78aed&e=171a097318>, follow us on Twitter @ViapathUK<http://viapath.us10.list-manage1.com/track/click?u=650308f65b655be63608468c8&id=c342df3db0&e=171a097318> and connect with us on LinkedIn<http://viapath.us10.list-manage.com/track/click?u=650308f65b655be63608468c8&id=bbbdf7ad55&e=171a097318>.

**Comment by AmyAmelia** [comment]
should be there now. Sample re-run with current GATK pipeline
