### ISSUE TITLE
Urgent: Attaching result sheets in Moka

### ISSUE THREAD

**Issue by schuiie** [moka-guys/helpdesk#126]
Hello,

Currently we are printing out result sheets once an array has been checked. Please can we have the result sheet attach as a Testfile instead?

We will also need a new list showing the cases that are ready for authorisation. 

Please can this be prioritised.

Many thanks,

Sarah

**Comment by woook** [comment]
Can save result sheet as a test file and then open it to allow user to print if they like. This would be better than the current function where Moka prints it as this then freezes Moka for minutes.

**Comment by woook** [comment]
Waiting for rollout

**Comment by woook** [comment]
Waiting for rollout
