### ISSUE TITLE
WES - re-analysis case

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#127]
Hi guys,

We have gotten a request for a re-analysis and ned you to retreive the VCF for us. DNA140485 in run 161202_NB551068_0018_AH35VKBGX2_NGS104B_WES6

Cheers,

/Matt

**Comment by andyb3** [comment]
Emailed DNAnexus rep to request data retrieval from archive on 5/04/18. Received out of office until 9/04/18.

**Comment by MattiasJanssonviapath** [comment]
Any update on this?

**Comment by andyb3** [comment]
I received an email from our DNAnexus rep on 13th saying the files are ready for dearchiving and they are just awaiting billing information. I will chase this up today.

**Comment by MattiasJanssonviapath** [comment]
Hi Andy, any luck?

**Comment by andyb3** [comment]
Hi Matt, I'm afraid I'm still waiting for a response from our rep. When I last emailed I received another out of office reply, saying that he'll be back on 27th April (i.e. tomorrow). Sorry this is taking awhile! I will email him again tomorrow.

**Comment by MattiasJanssonviapath** [comment]
Eeeeh?

**Comment by andyb3** [comment]
Actually had an email about this this morning to say that the dearchiving has commenced! I will check now to see if it is done.

**Comment by andyb3** [comment]
Pleased to report the fastq files have now been dearchived. We will run them through our current pipeline and let you know when they're available in Ingenuity.

**Comment by andyb3** [comment]
Done.
