### ISSUE TITLE
NGS212 samples missing

### ISSUE THREAD

**Issue by helenstorey** [moka-guys/helpdesk#128]
Hi, I don't know if they're just taking their time, but some of the samples on NGS212 are missing from Ingenuity.  Some are in there and have been most of the day, but quite a few are missing.

Many thanks
Helen

**Comment by andyb3** [comment]
Hi Helen,

There is an issue with the NextSeq which has caused this run to fail. An Illumina engineer is looking into it. I have just forwarded an email to you regarding this. Please avoid analysing any of the samples from this run.

Thanks,
Andy

**Comment by helenstorey** [comment]
Hi

Thanks for letting me know – sorry, I’m working from home and no one mentioned it!

Many thanks
Helen
