### ISSUE TITLE
TTN analysis from old sample

### ISSUE THREAD

**Issue by rachaelmein** [moka-guys/helpdesk#136]
Please could this sample be run through DNA nexus, added to Ingenuity and coverage report produced.  I only wish to analyse TTN but I think you used the CMCMD panel for coverage last time (Pan1464).

NGS41c_48_139237_AK_CM_AAAGCA

FASTQ file can be found on External Hard Drive Goofy

Thank you
Rachael

**Comment by rachaelmein** [comment]
Sorry here is another one to also analyse for TTN NGS41b_27_91571_NB_CM_GGCTAC

**Comment by aledj2** [comment]
Thanks for all the info, it was very helpful! Have set these running. They should be in Ingenuity (interpretation.request account) this afternoon. 

Where would you like the coverage reports saving?

**Comment by aledj2** [comment]
samples are in ingenuity. coverage reports were emailed.
