### ISSUE TITLE
WES - Statuses

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#138]
Hi Guys,

We seems to have a new status 'Pending' in our dropdown lists. Is there a reason why this one has appeared?

Cheers, /Matt

**Comment by aledj2** [comment]
Hi Matt, It's a change to the back end database so we can use the same database table to hold 100K tests. Is it an issue?
Thanks,
Aled

**Comment by MattiasJanssonviapath** [comment]
Not really an issue, just wondered as it's not a status we use. Same reason for the status name changes then?
Cheers, /Matt

**Comment by aledj2** [comment]
yea, exactly.
