### ISSUE TITLE
WES Results page - Reporting signature and date

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#139]
Hi guys,

Could we have the signature and date be uncoupled for the Report signature, please? (same functionality as the Assigned and Checked signatures)

Cheers, /Matt

**Comment by woook** [comment]
I would like signatures reviewed to ensure consistency across Moka.

**Comment by woook** [comment]
Reviewed - this is consistent with the rest of Moka.
