### ISSUE TITLE
Alports NGS samples needed

### ISSUE THREAD

**Issue by helenstorey** [moka-guys/helpdesk#140]
Hi

I need all the alports samples (ALP) off the following NGS batches to be put back in ingenuity at some point please. 
NGS180
NGS182
NGS184
NGS186
NGS188
NGS190
NGS192
NGS194
NGS196
NGS198
NGS202
NSG203
NGS204
NGS206
NGS208

I realise this will take up a lot of space in ingenuity but if just a few batches could be loaded to start with, that would be very helpful.

Many thanks
Helen

**Comment by AmyAmelia** [comment]
Re analysis required due change in filter setting in IVA.
NGS180- done
NGS182-done
NGS184rpt/186_done
NGS188 done
NGS190 done
NGS192 done
NGS194 done
NGS196 done
NGS198 done
NGS202 done
NSG203 done
NGS204 done
NGS206 done
NGS208 done
