### ISSUE TITLE
Access to phenotips for Jodie?

### ISSUE THREAD

**Issue by SueLillis** [moka-guys/helpdesk#142]
Please can Jodie have a log-in for phenotips?
Her email address is Jodie.Yates@viapath.co.uk

Many thanks
Sue

**Comment by AmyAmelia** [comment]
Hi Sue,
Jodie will need to register herself as a new user on our phenotype server. She can do this when logging into phenotips, there should be an option to set up a new account/ user. 

Best wishes
Amy

**Comment by SueLillis** [comment]
Fab, thanks Amy!
