### ISSUE TITLE
Add Jodie's initials to Moka please?

### ISSUE THREAD

**Issue by SueLillis** [moka-guys/helpdesk#143]
Please can Jodie Yates be added for selection in the drop-down boxes in Moka?
Yates Jodie <Jodie.Yates@viapath.co.uk>  

Thanks
Sue

**Comment by AmyAmelia** [comment]
HI Sue,

This is mostly done however I need Jodie's trust username to ensure all features can be used.
please can you let me know this.

thanks

**Comment by AmyAmelia** [comment]
Hi Sue,

I also need to know what initials Jodie uses in gene works to ensure consistency. 
Ta

**Comment by AmyAmelia** [comment]
All done :)
