### ISSUE TITLE
WES analysis streamlining

### ISSUE THREAD

**Issue by SueLillis** [moka-guys/helpdesk#148]
We've already discussed this issue with Andy but have been asked to raise a github issue too. 

Is there a way to import ' homo count no. in gnomAD from the ingenuity into Moka? And is there a quick way for us to highlight and discount these variants in Moka?

We estimate that this ability could save each scientist around 1.5 hour a week.   This equates to ~24 hours a month in total! 

Happy to discuss further if required.  Many thanks

**Comment by AmyAmelia** [comment]
Hi Sue,
Please can you let me know the hom count value you would like to be the threshold for a variant to be grayed out. 

Thanks
Amy

**Comment by AmyAmelia** [comment]
Following disscussion with Matt threshold was set to >= 3
