### ISSUE TITLE
NGS215

### ISSUE THREAD

**Issue by keziabrown** [moka-guys/helpdesk#150]
Is there any data for NGS215 available? Nothing has gone into the Ingenuity account today.

Thanks
Kezia

**Comment by AmyAmelia** [comment]
Hi Kezia,
Apologies, the new panels included in this run highlighted a bug in the automation code. This has now been fixed and the samples are now running through DNAnexus. Unfortunately it is unlikely they will be ready today. I shall send an email out now as well.

Amy
