### ISSUE TITLE
Alamut link to Polyphen

### ISSUE THREAD

**Issue by jocampbell** [moka-guys/helpdesk#155]
The link out from Alamut to Polyphen has not been working for several months.  When we press the button it opens a window but nothing ever loads.  It used to work fine, and I asked other centres on the variant investigation group call on Monday and other sites are still able to link out to Polyphen.  They suggested checking to see if there is a Firewall blocking the site.
Would someone please be able to check this as I have no idea how to?
This is on the Kings computer in the lab.
thanks
Jo

**Comment by aledj2** [comment]
Hi Jo,
It's not the proxy as other links work. I suspect the URL used to access polyphen is wrong but I couldn't see anyway of changing it. Looks like something to chase up with the Alamut suppliers I'm afraid.
Aled

**Comment by jocampbell** [comment]
Hi Aled,

Thanks for checking, I will get onto the Alamut tech support.

Cheers

Jo

Joanna Campbell PhD | Viapath
Clinical Scientist
Molecular Genetics
5th Floor Tower Wing |Guy's Hospital| London | SE1 9RT
020 7188 1714 (Tel)
020 7188 1697 (Fax)
joanna.campbell@viapath.co.uk<mailto:joanna.campbell@viapath.co.uk>
joanna.campbell3@nhs.net<mailto:joanna.campbell3@nhs.net>
A unique partnership of clinical, scientific and operational expertise, on a mission to transform pathology services in the UK.

Find out more at www.viapath.co.uk<http://viapath.us10.list-manage.com/track/click?u=650308f65b655be63608468c8&id=a65cf78aed&e=171a097318>, follow us on Twitter @ViapathUK<http://viapath.us10.list-manage1.com/track/click?u=650308f65b655be63608468c8&id=c342df3db0&e=171a097318> and connect with us on LinkedIn<http://viapath.us10.list-manage.com/track/click?u=650308f65b655be63608468c8&id=bbbdf7ad55&e=171a097318>.

**Comment by jocampbell** [comment]
Hi Aled,

I’ve been looking into this a bit more.  We’ve realised that we can’t get Polyphen-2 to load properly using any of the browsers on the Alamut computer.  We are able to use Polyphen-2 using Chrome, Firefox and Explorer on the Trust PCs, so I wonder if this is an issue with the King’s network?  Michael had a look and couldn’t work out what the problem was.  But he was also unable to get Polyphen-2 to load on the King’s PC in his office.

Attached is are screenshots showing what happens when we try to load Polyphen-2 using Alamut (which I think uses Explorer – I don’t think we have any way to change this), Chrome, Firefox and Explorer.  It partially loads using Chrome and Firefox, but the grid to select the wild type and mutant amino acid is not visible so we can’t actually use it.  The last screenshot shows how it appears on a trust PC – I’ve tested it on all 3 browsers and it works fine.

I haven’t contacted the Alamut tech support yet as I’m sure they are going to say it is an issue with our PC or network.  Any other ideas? I’ve cc’d Wook in case he has any thoughts.  If neither of you have any ideas Michael suggested I try Peter Botcherby next.

http://genetics.bwh.harvard.edu/pph2/

thanks

Jo

Joanna Campbell PhD | Viapath
Clinical Scientist
Molecular Genetics
5th Floor Tower Wing |Guy's Hospital| London | SE1 9RT
020 7188 1714 (Tel)
020 7188 1697 (Fax)
joanna.campbell@viapath.co.uk<mailto:joanna.campbell@viapath.co.uk>
joanna.campbell3@nhs.net<mailto:joanna.campbell3@nhs.net>
A unique partnership of clinical, scientific and operational expertise, on a mission to transform pathology services in the UK.

Find out more at www.viapath.co.uk<http://viapath.us10.list-manage.com/track/click?u=650308f65b655be63608468c8&id=a65cf78aed&e=171a097318>, follow us on Twitter @ViapathUK<http://viapath.us10.list-manage1.com/track/click?u=650308f65b655be63608468c8&id=c342df3db0&e=171a097318> and connect with us on LinkedIn<http://viapath.us10.list-manage.com/track/click?u=650308f65b655be63608468c8&id=bbbdf7ad55&e=171a097318>.

**Comment by aledj2** [comment]
Hi Jo,


Amy has found that the website appears to be blocked from the KCL network (same computer/browser works on other networks). It partially loads on firefox but is not functional. I think Peter Botcheby would be a good person to try next.


Aled

Aled Jones
Clinical Bioinformatician
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: aledjones@nhs.net
________________________________
