### ISSUE TITLE
WES custom coverage report

### ISSUE THREAD

**Issue by hkuoppamaa** [moka-guys/helpdesk#162]
Hi,

Could a coverage report for DNMT3A gene only be generated for NGS Test ID 825 (PRU 434195:01) please?

Thanks,
Heidi

**Comment by aledj2** [comment]
Hi Heidi,


I think you'll need to create a new panel containing that single gene.

ta,


Aled

Aled Jones
Clinical Bioinformatician
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: aledjones@nhs.net
________________________________

**Comment by aledj2** [comment]
ok thanks. I'll close this but re-open it if you need any more help!
