### ISSUE TITLE
NGS data required

### ISSUE THREAD

**Issue by helenstorey** [moka-guys/helpdesk#166]
Hi

Could the data for the following two patients please be put back on Ingenuity:

NGS184_16_186525_JT_ALP_Pan1451_S16_R1_001.refined 
NGS198_08_192017_GB_M_ALP_Pan1451_S8_R1_001.refined   

Thanks very much
Helen

**Comment by AmyAmelia** [comment]
Should now be in ingenuity for you.

**Comment by helenstorey** [comment]
Thanks!rom: AmyAmelia [mailto:notifications@github.com]
Sent: 10 May 2018 14:46
To: moka-guys/helpdesk <helpdesk@noreply.github.com>
Cc: Storey Helen <Helen.Storey@viapath.co.uk>; Author <author@noreply.github.com>
Subject: Re: [moka-guys/helpdesk] NGS data required (#166)


Should now be in ingenuity for you.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<http://scanmail.trustwave.com/?c=8248&d=0MT02gTpGAWf-xlmsCrPtUZO-vDNZv4901BWbpgRlw&u=https%3a%2f%2fgithub%2ecom%2fmoka-guys%2fhelpdesk%2fissues%2f166%23issuecomment-388057759>, or mute the thread<http://scanmail.trustwave.com/?c=8248&d=0MT02gTpGAWf-xlmsCrPtUZO-vDNZv490wYHPZhBwQ&u=https%3a%2f%2fgithub%2ecom%2fnotifications%2funsubscribe-auth%2fAfL8VRdfQx0vwKtSHCUvgWgljhx5VM9lks5txESbgaJpZM4T5tPC>.

*************************************************************************************

The information contained in this message and or attachments is intended only for the
person or entity to which it is addressed and may contain confidential and/or 
privileged material. Unless otherwise specified, the opinions expressed herein do not
necessarily represent those of Guy's and St Thomas' NHS Foundation Trust or 
any of its subsidiaries. The information contained in this e-mail may be subject to 
public disclosure under the Freedom of Information Act 2000. Unless the information 
is legally exempt from disclosure, the confidentiality of this e-mail and any replies
cannot be guaranteed.

Any review, retransmission,dissemination or other use of, or taking of any action in 
reliance upon, this information by persons or entities other than the intended
recipient is prohibited. If you received this in error, please contact the sender
and delete the material from any system and destroy any copies.

We make every effort to keep our network free from viruses. However, it is your
responsibility to ensure that this e-mail and any attachments are free of viruses as
we can take no responsibility for any computer virus which might be transferred by 
way of this e-mail.

*************************************************************************************
