### ISSUE TITLE
Old WES case - find deletion breakpoints

### ISSUE THREAD

**Issue by andyb3** [moka-guys/helpdesk#168]
> ...in-house WES testing identified a missense variant in the IFT140 gene which would fit with the diagnosis if a second variant in this gene was found.  Manchester have detected large intragenic duplication in this gene by NGS panel testing but can’t map the breakpoint.   
>  
> Please can we retrieve the WES data to see if the location of the intragenic duplication can be determined?

See paperwork attached to email from Sue L

**Comment by andyb3** [comment]
Data in 002_180510_140485_167781_WES_reanalysis

**Comment by MattiasJanssonviapath** [comment]
This has been completed

Cheers, Matt
