### ISSUE TITLE
Analysis on Windows10

### ISSUE THREAD

**Issue by mikecoldwell** [moka-guys/helpdesk#17]
Dragging and dropping files into OLE objects is painfully slow on the Windows10 computer and there is an error message
![error attaching screenshots](https://user-images.githubusercontent.com/30150373/33834392-b6e41e4a-de7a-11e7-86d9-52fc91dfff83.png)
I think this error message popped up if I was too quick for the page but there may have been some other unexplained reason for this message. In either case the message did not force Moka to close and seemed to be ignorable. The length of time it took the "batched array OC" and "batched test files list" to update was a bigger issue than the error message itself.

**Comment by andyb3** [comment]
We were planning to try and move away from OLE files anyway. Perhaps we could try and have a rethink about how this is done

**Comment by andyb3** [comment]
Is this working correctly now?
