### ISSUE TITLE
NGS sample required on Ingenuity

### ISSUE THREAD

**Issue by helenstorey** [moka-guys/helpdesk#171]
Sorry, could I have the following sample put on ingenuity please:

NGS184Rpt_16_186525_JT_ALP_Pan1451

thanks very much
Helen

**Comment by andyb3** [comment]
Hi Helen,

The above sample is included on the NGS184 run but not the NGS184rpt run. Do you happen to know why this run was repeated?

Thanks,
Andy

**Comment by andyb3** [comment]
Hi Helen,

Thanks for the update. Glad you've found what you need!

Andy
