### ISSUE TITLE
Changing an amplicon name - primer database

### ISSUE THREAD

**Issue by JodieYates** [moka-guys/helpdesk#173]
Hey :) 

There are two primers that accidentally got added as a DDD prefix but are actually for GeL; Would it be possible to change the name to GeL_.......? Is there a way I can do this myself (I cant find it if there is)? Or is this only possible by raising an issue on here? This is Low priority so just whenever you have a spare minute :) 

Primer 1214 DDD_DNM1_Met332_01
Primer 1215 DDD_DNM1_Met332_02

Thanks!

**Comment by aledj2** [comment]
Done. Some fields can't currently be changed through the user interface so any further changes to these fields will need a github issue.
Thanks,
Aled
