### ISSUE TITLE
Viewing primer sequences in Primer test results page

### ISSUE THREAD

**Issue by JodieYates** [moka-guys/helpdesk#178]
As the title says .... would it be possible to view primer sequences in the primer test results page (those awaiting testing)? A couple of people have commented that it would be really useful to them.

Many thanks

Jodie :)

**Comment by aledj2** [comment]
Hi Jodie, 
I think I've had this request before from one person and after a wider discussion it was decided it wouldn't be useful. Why exactly would the sequences be useful?
Thanks

**Comment by JodieYates** [comment]
Hey,
It was Rachael and Wendy who mentioned that they do some checking of the primer sequences (they'll be able to tell you better than me); they both said they had to pass them before testing was complete in order to view the sequences. 
Jodie

**Comment by aledj2** [comment]
This should now be in Moka
