### ISSUE TITLE
NGS WES Panel issue

### ISSUE THREAD

**Issue by beth-wild** [moka-guys/helpdesk#180]
Trying to create a tertiary panel (intellectual disability 1701 and callosome 1538). When copying and pasting callosome genes into the panel page, an error message appears reading "the text is too long to be edited". 
We think it might be because there are a lot of genes in both of these panels - we have never made a tertiary panel with this many genes before.
PRU 339182:01
DNA 153186

**Comment by aledj2** [comment]
oh dear. Is your tertiary panel containing only those two panels?

**Comment by aledj2** [comment]
when copying and pasting the list of genes into the panel, are you highlighting the gene column before pasting the symbols? (rather than just putting the cursor in the gene field in the top row?)

**Comment by aledj2** [comment]
Any luck with this?

**Comment by beth-wild** [comment]
Hi Aled,
Yes - we have just been putting the cursor in the first gene name and highlighting down from there (not including the "GENE" column title).
Sorry for the late reply, I was not checking my NHS.net email address

**Comment by beth-wild** [comment]
Yes, it is just those 2 panels

**Comment by aledj2** [comment]
Coverage report will be fine with duplicate genes but not sure what else it could impact. I'll close this issue now, let me know if you have any other problems.
Ta

**Comment by beth-wild** [comment]
?Hi Aled,


That's great - thanks!

________________________________
