### ISSUE TITLE
Delete cancelled WES request from Moka

### ISSUE THREAD

**Issue by SueLillis** [moka-guys/helpdesk#181]
Please can the incomplete WES test request for PRU444529 be deleted from Moka. The clinician has cancelled the testing. This case was brought to my attention by Amy yesterday. 
Many thanks
Sue

**Comment by woook** [comment]
This type of case shouldn't be deleted but rather the test status should be set to "not required" and a note recorded explaining way.


Don't mind who does that as long as it's not deleted.


Thanks,


Wook

________________________________

**Comment by SueLillis** [comment]
Thanks for the update Wook.
Unfortunately using my Moka log in, the sample isn’t visible on the DNA QC dashboard. Although I can see it via ‘Exome Status’
Can one of you please change the status to ‘not required’ please.
Many thanks
Sue

**Comment by andyb3** [comment]
Done
