### ISSUE TITLE
Comment area on PGD array CGH reports is too small

### ISSUE THREAD

**Issue by AngelaDavies** [moka-guys/helpdesk#186]
Please could the comment area that allows free-typing on the PGD array CGH reports be made larger? Twice the current size would be good and would allow for the occasional unusual report that requires a longer comment.

**Comment by AngelaDavies** [comment]
It's on Patient Details on the PGD cycles tab

**Comment by aledj2** [comment]
This has been done -awaiting roll out (see also #261)
