### ISSUE TITLE
WES coverage report error

### ISSUE THREAD

**Issue by SueLillis** [moka-guys/helpdesk#187]
Error message when generating coverage report for PRU339182:01

WARNING: 2 genes are present in the gene panel which are not in exome bedfile.

![pru339182_01](https://user-images.githubusercontent.com/30261729/40771548-897fabce-64b5-11e8-804b-af8235c381cd.PNG)

**Comment by aledj2** [comment]
Hi Sue,
To identify the genes which panel(s) are you trying to create the coverage report for? The missing genes are usually non coding genes

**Comment by SueLillis** [comment]
Thanks for the prompt reply Aled

The panels are 1172 and 2154 which are combined panels (Pan2154) was the one you helped Beth with yesterday.
How do I find out which are the non-coding genes on these panels?

**Comment by aledj2** [comment]
The genes are:
DWS (HGNC:3088)
MRT4 (HGNC:33243)
They both have a locus type of 'phenotype only' and don't have coding regions so we can't calculate coverage!

**Comment by SueLillis** [comment]
Many thanks Aled
Sue
