### ISSUE TITLE
Samples to Ingenuity

### ISSUE THREAD

**Issue by rachaelmein** [moka-guys/helpdesk#189]
Please can you put the following samples back into ingenuity;
NGS179B_29_184129_RH_CMCMD
NGS179B_20_185202_AA_CMCMD
NGS163B_36_167643_JO_CM_CMD
NGS163B_29_174240_SN_CM_CMD
NGS163A_01_155998_MH_CMD

Many thanks
Rachael

**Comment by AmyAmelia** [comment]
Should be back in there in a few moments.

**Comment by rachaelmein** [comment]
Hi This one is not there??
NGS163A_01_155998_MH_CMD
