### ISSUE TITLE
Move away from GW views in admin FE

### ISSUE THREAD

**Issue by aledj2** [moka-guys/helpdesk#193]
A complaint about speed of a GW query was raised with IT. 
A historical request to add indexes to GW views was re-raised as a solution, but we were also asked to ensure Moka used the GW server efficiently, eg not having queries without where clauses.

The record source for form 6003 (in admin FE) was blamed for slowing down GW due to a lack of a where clause.
Investigating this showed GW views were used and we are trying to move to using moka views of the GW views.

**Comment by aledj2** [comment]
Views have been created in Moka. Email sent to GW requesting views are indexed sufficiently

**Comment by aledj2** [comment]
look for query which uses tbl1001 and SpecimenLinked table as this seems to affect GW performance

**Comment by woook** [comment]
What is tbl1001?

________________________________

**Comment by aledj2** [comment]
The name in a query identified by Andrew as one without a where clause
Aled

Aled Jones
Clinical Bioinformatician
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: aledjones@nhs.net

________________________________________

**Comment by woook** [comment]
What is contained in this table?

I don't recognise it...

________________________________

**Comment by aledj2** [comment]
This issue has mutated. The record source for 6003 has been addressed in #214. Any views which use the geneworks2jenny ODBC link have been replaced by moka views. However this just enables the query to be run from any machine/user.

The GW performance issues are being investigated with Andrew Marsh. He has identified some queries which are hanging, or not completing and the MAC address of those machines . Current suspect is the moka booking on process

**Comment by NMNS93** [comment]
Aled sat with Andrew Marsh to investigate this particular query and the conclusion was - if this query is causing the problem, it is only sporadic so it isn't the main cause of the issue. 

It was suspected that a MAC address used for booking on could be the cause. We are looking at optimising the booking on in #251 .
