### ISSUE TITLE
NGS Test ID 879 cov report (previous name and missing HPE1)

### ISSUE THREAD

**Issue by RachaelIrwinViapath** [moka-guys/helpdesk#195]
NGS Test ID 879, DNA 180545, WES 20

The coverage report for the above case has the previous name for the patient (both forename and surname are now different, not sure if I'm okay to write them here but they're in the Moka comments!). Also when I was creating the coverage report I got an error message that one of the genes was not in the exome BED file, and HPE1 is missing so I think it must have been referring to that one (I've checked it on Ingenuity and HPE1 is on the panel there, but flagged as unmapped). Is it possible please to get a new coverage report which has the current patient name and includes HPE1? Thank you!

**Comment by andyb3** [comment]
Hi Rachael. We'll look into this for you. (And you were right not to put the patient name on here!)

**Comment by AmyAmelia** [comment]
Hi Rachael,
I have updated the name for you. In future, if the names in GW and Moka differ, you should click the patient page button at the top right hand page of the NGS results it will link you through to a page in MOKA that checks that GW and MOKA are the same. A pop up should be displayed asking if you wish to update MOKA.  Just follow the prompts. This might be something worth including in your SOPs.
I have also re-run the coverage report, so the patient name is now correct but I still need to investigate the missing gene and will get back too you on that asap.

**Comment by AmyAmelia** [comment]
Re: missing HPE1 from the coverage report; HPE1 has a locus type of 'phenotype only' and therefore doesn't have coding regions or genomic locations as a result we can't calculate coverage for this gene.
