### ISSUE TITLE
WES - request for archived data

### ISSUE THREAD

**Issue by hkuoppamaa** [moka-guys/helpdesk#196]
Hi,

Could we get the VCF file from the archive for PRU 349724:01 DNA#145174 please?

Thanks,
Heidi

**Comment by aledj2** [comment]
Hi Heidi, 
What do you need this VCF for? 
Thanks,
Aled

**Comment by hkuoppamaa** [comment]
Hi Aled,

Some additional analysis has been requested by the clinician.

Thanks,
Heidi

**Comment by aledj2** [comment]
It's on it's way to ingenuity, shared with the gst-tr.wesviapath.nhs.net.
Feel free to re-open this issue if you need anything else
