### ISSUE TITLE
Data for NGS222

### ISSUE THREAD

**Issue by keziabrown** [moka-guys/helpdesk#197]
Is the data for NGS222 expected? It's not come up in Ingenuity yet. Could it have been interrupted due to the power outage?

**Comment by aledj2** [comment]
Hi Kezia. 
Thanks for the prompt, the data should be with you by the end of the day.

**Comment by keziabrown** [comment]
Thanks Aled. What's the earliest the data might be available? There are 3 BRCA Rapids on this run due today so ideally need it asap.

**Comment by aledj2** [comment]
It's going to be at least 4pm I'm afraid
