### ISSUE TITLE
(moka) Change to emails sent for 100K results

### ISSUE THREAD

**Issue by woook** [moka-guys/helpdesk#198]
Following a process change for sending reports to genetics clinic, all emailed reports should be sent to GeneticsResults@gstt.nhs.uk
This could be achieved by changing the email address in the Checkers table in Moka but not sure if that would break anything else?

In addition, the subject of the email should be updated to the following:

100,000 Genomes Project Result

and the body of the email should be updated to the following:

**100,000 Genomes Project result from the Genetics Laboratory at Viapath  - Guy's Hospital**

PLEASE DO NOT REPLY TO THIS EMAIL ADDRESS WITH ENQUIRIES ABOUT REPORTS
FOR ALL ENQUIRIES PLEASE CONTACT THE LABORATORY USING DNADutyScientist@viapath.co.uk

Kind regards
  
Genetics Laboratory 
5th Floor, Tower Wing              
Guy’s Hospital
London, SE1 9RT                                  
United Kingdom

Tel: + 44 (0) 207 188 1709

**Comment by andyb3** [comment]
The WES ordering system uses the clinician email addresses to send notification emails so don't think we can change those. Perhaps could update the reporting python script so that if Checker.Address == 2198 it uses GeneticsResults@gstt.nhs.uk instead of Checker.Email?

**Comment by aledj2** [comment]
add result email address field in checker table

**Comment by aledj2** [comment]
ready for code review https://github.com/moka-guys/GeL_Reports/pull/19. 
Can then release on Github and close Q-Pulse audit (Validation)

**Comment by woook** [comment]
Ready for release

**Comment by aledj2** [comment]
@woook  please close audit 416

**Comment by woook** [comment]
Check if this has been released.

**Comment by aledj2** [comment]
Have moved to production. needs a quick test from Moka and then the audit completed. AJ to do
