### ISSUE TITLE
Adding dilution tray column to primer database

### ISSUE THREAD

**Issue by JodieYates** [moka-guys/helpdesk#199]
Could we please have an extra column to record the tray the dilutions are stored in? It would be great to have it free text to input the tray name/number. 

This should be visible in both primer test results and approved primers as dilutions are made as soon as primers arrive, prior to testing. For some disease work these dilutions are kept for a long time so will still be in use after approving. 

Thanks

**Comment by aledj2** [comment]
Hi Jodie,
I'm afraid we're really busy at the moment so unless this is something which will stop the database from being used we can't add this at the moment.
Thanks,
Aled
