### ISSUE TITLE
WES case sharing

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#2]
Hi guys,

Can all current cases not previously shared with us be shared with Andy's account? This would enable us to share samples with ourselves without having to bother the bioinformatics team.

When our generic WES email is active we can set up an automatic sharing of new cases using that email.

Cheers, /Matt

**Comment by MattiasJanssonviapath** [comment]
Hi,
These are the runs that we haven't had shared with us. Unfortunately we don't know when the new account will be up, and we need samples now. The samples we need the most have priority requests so I think it would be more work to go in and resubmit several runs from DNAnexus just to share one or two cases with us. If we get everything now we can then transfer everything from Andy's account to the WES account ourselves.
170920_NB551068_0062_AHLL25BGX3_NGS185A_WES17
170925_NB551068_0064_AHMNWJBGX3_NGS185B_WES17
171002_NB551068_0066_AHLKYMBGX3_NGS185C_WES17
171018_NB551068_0072_AHTCNHBGX3_NGS189A_WES16_WES19
171025_NB551068_0075_AHW3FTBGX3_NGS189B_WES19
171101_NB551068_0077_AHW3MLBGX3_NGS189C_WES19
171106_NB551068_0079_AHWW7LBGX3_NGS189D_WES19
171115_NB551068_0080_AH2TGWBGX5_NGS193A_WES19_WES20
171122_NB551068_0082_AH3M2LBGX5_NGS193B_WES20
Cheers, /Matt

**Comment by andyb3** [comment]
OK no problem, I'll get them submitted asap

**Comment by andyb3** [comment]
They're now in my account
