### ISSUE TITLE
Windows10 Error printing to PDF

### ISSUE THREAD

**Issue by mikecoldwell** [moka-guys/helpdesk#20]
I was analysing a prenatal sample and needed to print to PDF. The first issue was that I could not view any other page in moka while trying to print a page using microsoft print to PDF, this meant that I had to copy the hyb ID, the name and the specimen number to a test file first. The second issue was that microsoft print to PDF does not seem to produce valid PDF when printing from Moka (I checked and it works properly with word)

**Comment by andyb3** [comment]
We tried this again today and it seemed to be saving the PDF correctly now. However this won't solve the first issue. If the filename is always the same format, what if we displayed the information required for the filename on the same page that is printed to PDF so it is easy to copy and paste?
