### ISSUE TITLE
This is now sorted ! Coverage report - error when generating for PRU339454_01

### ISSUE THREAD

**Issue by SueLillis** [moka-guys/helpdesk#201]
![pru339454_01](https://user-images.githubusercontent.com/30261729/41360408-9c1faea4-6f24-11e8-8742-c546cd41011e.PNG)

**Comment by aledj2** [comment]
Hi Sue,

Just to confirm the report we have just made is correct.

I don't know how to identify cases that were run through the pipeline again as part of the re-analysis. I don't know why this was done for this case.

FYI the 5 genes are:
HGNCID,Symbol
HGNC:32952,SNORD118
HGNC:7414,MT-ATP6
HGNC:7455,MT-ND1
HGNC:7459,MT-ND4
HGNC:7489,MT-TK

thanks,
Aled
