### ISSUE TITLE
URGENT: Back-up files from instrument room computer

### ISSUE THREAD

**Issue by schuiie** [moka-guys/helpdesk#202]
Hello Bioinformatics,

Our computer in the instrument room is running out of space. We have been deleting some data from it once we have transferred them to the S drive using a USB stick. However, we have lots of large image files that have not been backed up and our NAS is not working. Please can all the files be backed up to DNAnexus? We only have enough space on our computer for about three more array runs so please can this be processed urgently?

Thanks very much!
Sarah

**Comment by Graeme-Smith** [comment]
Open as new issue #287
