### ISSUE TITLE
WES - Retreive archived sample

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#205]
Hi guys,

Can I have the VCF from PRU294396:01 DNA119886 WES6 retreived from archive, please?

Cheers,

/Matt

**Comment by aledj2** [comment]
Hi Matt,
Can I check what this is required for (just to know whether it should be re-processed through the pipeline)
Ta
Aled

**Comment by MattiasJanssonviapath** [comment]
Hi Aled,

It's for a re-analysis request so re-processing is in order.

Cheers,

/Matt

**Comment by aledj2** [comment]
OK thanks Matt,
It's running through the pipeline now so should be in Ingenuity this afternoon.

**Comment by MattiasJanssonviapath** [comment]
Cheers have it now :)
