### ISSUE TITLE
WES - Exome level coverage

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#207]
Hi guys,

Can I have the average exome level coverage for the genes in the Rasopathy panel (Pan503), please?

Cheers, /Matt

**Comment by aledj2** [comment]
[Pan503_average_coverage.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0d18cf63e424001409b50b/125516c66e82c728ace21e0d46d8959476d2d0968effba51a55af5ab2a4931763b05a42e32c9a138ad4d71040c1b5ca6535d0d44a8f8817ef2b23926df5859edd16f5a76c66c43a9bc9003ad43eb7edf10d8eff6df0ed2e22f24e0818e4a3d1e07108dfe5f35a19b42da15.xlsx)

**Comment by MattiasJanssonviapath** [comment]
Hi Aled,

For this one I needed the exome level coverage.

Cheers, /Matt

**Comment by aledj2** [comment]
sorry, what do you mean by exome level coverage? for a particular case?

**Comment by MattiasJanssonviapath** [comment]
Sorry, should be EXON level coverage. My bad... The average coverage of the exons of the genes in the panel.

**Comment by aledj2** [comment]
Ah ok, that's a bit harder to do...


********************************************************************************************************************

This message may contain confidential information. If you are not the intended recipient please inform the
sender that you have received the message in error before deleting it.
Please do not disclose, copy or distribute information in this e-mail or take any action in relation to its contents. To do so is strictly prohibited and may be unlawful. Thank you for your co-operation.

NHSmail is the secure email and directory service available for all NHS staff in England and Scotland. NHSmail is approved for exchanging patient data and other sensitive information with NHSmail and other accredited email services.

For more information and to find out how you can switch, https://portal.nhs.net/help/joiningnhsmail

**Comment by aledj2** [comment]
Hi Matt.
I'm afraid this isn't something we have time to do at the moment. 
The average coverage of each gene is shown in the excel file I sent. They're all covered quite well, with the lowest gene covered at around 82%.  
If we created an average coverage of exons, or hotspots, this is no guarantee it'll always be covered.
If there is a more specific question, eg coverage of a specific hotspot we recommend looking at a handful of BAM files (it doesn't have to be the same dataset as used to calculate the average coverage).
Thanks,
Aled
