### ISSUE TITLE
Access to Moka Consumables for 4th Floor Cancer Genetics

### ISSUE THREAD

**Issue by TLKirby** [moka-guys/helpdesk#208]
4th Floor Cancer Genetics lab (formerly known as Molecular Oncology) would like to make use of the Moka: Consumables database to keep track of their orders, deliveries and expired items (as used by 5th floor Cancer Genetics aka Oncology).  Initially this would only be for Lead MTO Anushiya Rajakumar, but may be extended to other staff in her lab.  Please could you grant appropriate access to Moka for Nush, and assist in installing Moka to the required PCs on the 4th floor?

Nush would also require additional "Section"s adding for her team in Inventory Consumables, namely "CG Reagents" and "CG Consumables".

If required, Nicky Foot can give approval for this.

Thanks muchly,
Toby

**Comment by aledj2** [comment]
Hi Toby,
I believe moka can be installed by raising a call with It.
I'll have a chat re the sections tomorrow.
Ta

Aled

Aled Jones
Clinical Bioinformatician
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: aledjones@nhs.net

________________________________________

**Comment by aledj2** [comment]
Added users to checker table and sections to item table.
