### ISSUE TITLE
WES - EFTUD2

### ISSUE THREAD

**Issue by hkuoppamaa** [moka-guys/helpdesk#209]
Hi,

Would you be able to tell me which panels the EFTUD2 gene is in please?

Thanks,
Heidi

**Comment by aledj2** [comment]
It's in around 250 panels. Is there a type of panel you're particularly interested in? eg I can exclude inactive or panelapp panels from the list?

**Comment by hkuoppamaa** [comment]
Wowza! I'll check with the clinician who requested the info.

**Comment by woook** [comment]
Hi Heidi - this might be a bit more useful for the clinician:

https://panelapp.genomicsengland.co.uk/panels/entities/EFTUD2


W

________________________________

**Comment by hkuoppamaa** [comment]
Great, thanks! I'll pass that link on to the clinician. She said she will likely consider EFTUD2 due to VACTERL-like with bilateral microtia so the VACTERL-like panel seems appropriate.

**Comment by hkuoppamaa** [comment]
The clinician got the answer she was looking for, thanks!
