### ISSUE TITLE
WES - Variant list

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#211]
Hi guys,

My variant lists in the WES results page comes up sorted by gene name. I have tried deleting and downloading the database which sorted the issue before but it doesn't any more. The issue is both immediate and persistent. And really annoying.

Cheers, /Matt

**Comment by andyb3** [comment]
Looks like this is the case in the master copy too. Going to do a Moka roll out this afternoon which should fix this.

**Comment by woook** [comment]
Waiting for rollout
