### ISSUE TITLE
DNA EXPORT - QUERY 

### ISSUE THREAD

**Issue by lallan83** [moka-guys/helpdesk#214]
Please can I have permissions set up so that I can pull the Export DNA list over to the Query spreadsheet.

Many Thanks

Lisa

**Comment by woook** [comment]
Needs Lisa's user account to be added to Moka-Users AD group and Moka installed on her PC.

**Comment by aledj2** [comment]
Hi @lallan83 , what is your trust username (what you use to log into windows)
Ta
Aled

**Comment by lallan83** [comment]
lallan1

:o)

**Comment by aledj2** [comment]
ticket raised on service now - INC0021568

**Comment by aledj2** [comment]
Moka is already installed, and Lisa a member of the AD group. The error is an ODBC call fail. I think this is because it uses geneworks jenny new odbc link??

**Comment by aledj2** [comment]
ODBC link is geneworks2jenny. tables are dbo_dna_***.
Will need to change these tables and ODBC

**Comment by aledj2** [comment]
potential new querySELECT dbo_patientlinked.PatientTrustID AS [PRU No], dbo_patientlinked.LastName AS Surname, dbo_patientlinked.FirstName AS [First name], dbo_specimenlinked.SpecimenTrustID AS [Spec no], dbo_dnanumberlinked.DNANo AS [DNA #], " " AS [Vol sent], dbo_dnasendawaylinked.TestTypeExternalTest AS TestRequested, dbo_dnasendawaylinked.LaboratoryCode AS [Where sent], dbo_dnasendawaylinked.DateSent AS [Date Sent], dbo_specimenreferrallinked.ReferralOrganisation AS [Referring Hospital], [dbo_SpecimenReferralLinked].[FIRSTNAME] & " " & [ReferralPractitioner] AS Clinician, dbo_dnasendawaylinked.ExpectedCost AS [Estimated Cost], dbo_dnatestrequestlinked.DateRequested, dbo_dnatestrequestlinked.TestDescription
FROM (((((dbo_dnatestrequestlinked INNER JOIN dbo_TestLinked ON dbo_dnatestrequestlinked.TestID = dbo_TestLinked.TestID) LEFT JOIN dbo_dnasendawaylinked ON dbo_TestLinked.TestID = dbo_dnasendawaylinked.TestID) LEFT JOIN dbo_specimenlinked ON dbo_TestLinked.SpecimenID = dbo_specimenlinked.SpecimenID) LEFT JOIN dbo_patientlinked ON dbo_specimenlinked.PatientID = dbo_patientlinked.PatientID) LEFT JOIN dbo_specimenreferrallinked ON dbo_TestLinked.SpecimenID = dbo_specimenreferrallinked.SpecimenID) LEFT JOIN dbo_dnanumberlinked ON dbo_TestLinked.SpecimenID = dbo_dnanumberlinked.SpecimenID
WHERE (((dbo_dnatestrequestlinked.DateRequested) Between [Between period starting? eg 2/10/13] And [And period ending? eg 5/10/13 (set end date as the day after the one you want to include)]) AND ((dbo_dnatestrequestlinked.TestDescription)="Export DNA"))
ORDER BY dbo_dnasendawaylinked.DateSent;

**Comment by aledj2** [comment]
see https://github.com/woook/moka-fe/pull/521

**Comment by andyb3** [comment]
ready for roll out

**Comment by aledj2** [comment]
Changes copied to the development admin front end

**Comment by woook** [comment]
Needs release.

**Comment by aledj2** [comment]
Hi Lisa, This has been released now. Can you check it works please
