### ISSUE TITLE
Squashed results page

### ISSUE THREAD

**Issue by mikecoldwell** [moka-guys/helpdesk#216]
Now that widescreens are standard in the department can the array results page be spread out a little? I have noticed that the menu options along the top have already spread out beyond what would have fit on the old style monitors, but the results page itself is still boxed in. There are two tables on this page which are particularly squashed: the calls table, for which we need to scroll right every time we want to enter an comment, and the test file table, which keeps jumping to the right and hiding the contents of the 'Description' column.  Obviously this is not super urgent but it would save time and make moka a bit less irritating.  Thank you

Mike

**Comment by andyb3** [comment]
As luck would have it I had already widened the page to fit on some other changes I made that are queued up for the next release which should be happening later today.

**Comment by woook** [comment]
Waiting for rollout
