### ISSUE TITLE
WES - Average coverage of the Epilepsy panel

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#220]
Hi guys,

Can I have the average coverage of the genes in the Epilepsy panel (Pan1021) please.

Cheers, /Matt

**Comment by aledj2** [comment]
[Pan1021_average_coverage.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0d18cf63e424001409b50b/125516c66e82c728ace21e0d46d8959472d2d1f8b0e8a946b65cf791164528652c16a22c75c7af6aaf50740b0a0c0abe4b4a5a16fcad8823f3e23875dc090fbfd16d5d71c43d40febd860da313f871d51bdaebe5c01982fa3737e683854e3b1d051a81fc5f35a0994fcd4abb.xlsx)
