### ISSUE TITLE
Contact InsightOps support

### ISSUE THREAD

**Issue by woook** [moka-guys/helpdesk#222]

**Comment by aledj2** [comment]
email sent

**Comment by aledj2** [comment]
The inactivity alerts are not restarted until a new event occurs (eg the next heartbeat). 

We have installed ir_agent onto the workstation and updated the alerts to look at the new endpoint.

The existing heartbeat alert has been changed to alert if two consecutive heartbeats are missed to make it less sensitive.

Additional alerts will be set up with differing periods of inactivity in case the first alert is not seen/acted upon.

Additionally we will need to define what is done after a inactivity alert is seen (ie check that the heartbeats have started again).

**Comment by aledj2** [comment]
See service now article also
