### ISSUE TITLE
editing primer name

### ISSUE THREAD

**Issue by JodieYates** [moka-guys/helpdesk#225]
Oopsie I noticed a typo in this primer name 

BRCA_TP53_ex28_3_01_Legacy (frag id 1570)

Its supposed to be ex2_3 not 28! Could this be changed when you get a spare moment please? 

Thanks :)

**Comment by JodieYates** [comment]
Here is a few more I noticed: 

Frag ID |        Amplicon Name                    | Change    to                                                       
2530     | NMD_SE1_Ex3_01_Legacy            | NMD_SIL1_Ex3_01_Legacy
2531     | NMD_SE1_Ex4_01_Legacy            | NMD_SIL1_Ex4_01_Legacy
2532     | NMD_SE1_Ex5_01_Legacy            | NMD_SIL1_Ex5_01_Legacy
2533     | NMD_SE1_Ex6_01_Legacy            | NMD_SIL1_Ex6_01_Legacy
2534     | NMD_SE1_Ex7_01_Legacy            | NMD_SIL1_Ex7_01_Legacy
2535     | NMD_SE1_Ex8_01_Legacy            | NMD_SIL1_Ex8_01_Legacy
2536     | NMD_SE1_Ex9_01_Legacy            | NMD_SIL1_Ex9_01_Legacy
2537     | NMD_SE1_Ex10_01_Legacy          | NMD_SIL1_Ex10_01_Legacy
2538     | NMD_SE1_Ex11_01_Legacy          | NMD_SIL1_Ex11_01_Legacy
2539     | NMD_SE1_Ex14_01_Legacy          | NMD_SRPK3_Ex14_01_Legacy
2540     | NMD_SE1_Ex15_v1_Legacy          | NMD_ SRPK3_Ex15_v1_Legacy
2561     | NMD_TNNT1_Exint12_v1_Legacy | NMD_TNNT1_int12_v1_Legacy |  

Sorry! Obviously I was having a moment when I did these!

**Comment by aledj2** [comment]
Done, please check!
Thanks,
Aled

**Comment by JodieYates** [comment]
Hey,

2533, 2534, 2535 and 2537 still read SE1 instead of SIL1 on my screen. 
Also 2539 and 2540 should be SRPK3

Not sure if it's just not updated properly on my screen?

**Comment by aledj2** [comment]
sorry my bad, can you check if it's ok now please.
ta

**Comment by JodieYates** [comment]
All looks good apart from 2540 which has an L instead of K in SRPK3

Sorry!

**Comment by aledj2** [comment]
corrected that one too.
thanks!
