### ISSUE TITLE
To run through pipeline

### ISSUE THREAD

**Issue by rachaelmein** [moka-guys/helpdesk#231]
Please could the following sample be put through DNA Nexus, NGS130b_27_168060_MA_CM.  This is on an old run previously analysed by NextGene but now TTN analysis is requested.

The FASTQ file can be found on external hard drive Mickey.  Coverage report can be generated from Pan2022 and then I will just filter the table for TTN only.

Thanks
Rachael

**Comment by andyb3** [comment]
Hi Rachael,

Just to check, is this going in as a new diagnostic test and being billed as such? 

Thanks,
Andy

**Comment by rachaelmein** [comment]
Yes I guess so as I do not think it has been run through DNA nexus before as it is on an old run that was previously analysed via NextGene.

Rachael

**Comment by andyb3** [comment]
Ok. I had a quick look but couldn't see the fastq files for that run on Mickey. Could you
