### ISSUE TITLE
Moka changes requested by clinician

### ISSUE THREAD

**Issue by RachaelIrwinViapath** [moka-guys/helpdesk#233]
Hi bioinformatics team,

I've had a few requests for changes to Moka from the clinicians (communicated by Francesca Forzano):

1. Could they have a Comments box, to enable them to e.g. flag certain genes for prioritisation during analysis, or communicate other info to us without needing to write an email

2. Could they have access to the Priority checkbox (again to replace the need for sending an email)

3. Would it be possible for them to see the gene lists prior to ordering a test? To help them with deciding the most appropriate test (Francesca says the gene list is currently the last bit they get to see, after the test has already been ordered)

I'm afraid I'm unfamiliar with the view of Moka currently available to clinicians, so I'm not sure on the feasibility of any of this. I also appreciate how extremely busy you are! I have advised Francesca that due to this, if the changes are possible, they can't be rapidly implemented. We're having a meeting on Wednesday, so if you could possibly get back to me just with an indication of whether these changes are feasible (or indeed sensible) by then, that'd be great!

Thank you,
Rachael

**Comment by aledj2** [comment]
Hi Rachael,

I'm afraid we don't have the resources to address all these issues at the moment, please could you suggest that the clinicians use PanelApp to look at panels before ordering.

Thanks,
Andy

**Comment by RachaelIrwinViapath** [comment]
Hi Andy,

Thanks for your reply, I thought that may be the case and will let the clinicians know in our meeting tomorrow. Am I correct in thinking that the PanelApp strategy will only work if they want to select a PanelApp panel, and not for our internal panels?

Thanks,
Rachael

________________________________
