### ISSUE TITLE
Ingenuity Summer 2018 Release- Verification

### ISSUE THREAD

**Issue by SueLillis** [moka-guys/helpdesk#234]
We are running our validation of Ingenuity after the latest software update. 

The latest version has successfully retained the correct number of variants for both our of 'test' cases (73 class 4/5 variants, 54 class 3 variants).  The VCF output files from Ingenuity have been successfully imported into Moka. 

We now need someone from the bioinformatics team to compare the output files from this release against the previous release.  This was agreed at a WES/bioinformatics meeting recently and aims to prevent any slight changes to the data going unnoticed. 

I cannot seem to upload the VCF files here, but have emailed them to gst-tr.mokaguys@nhs.net
Thanks 
Sue

**Comment by andyb3** [comment]
Hi Sue,

I have compared the VCF headers to the previous release. The only changes are database version numbers (which is to be expected). It doesn't look like there are any changes in format to existing fields, or new fields added.

I did notice that Ensmebl transcripts are now being included alongside the RefSeq transcripts in the VCF. This shouldn't break anything, but does mean that you will have more rows for each variant in Moka.

Happy for you to sign this off.

Andy

**Comment by SueLillis** [comment]
Hi Andy,

Thanks very much for doing this.
Yes we are aware of the addition of Ensembl transcipts which will clutter up Moka for us.

There also appears to be an issue with file sharing. We cannot share analysis files created before June 2018.   Matt has contacted Qiagen to see what the story is.    This could be a massive problem for the way we work!

Keep you posted

Thanks
Sue
