### ISSUE TITLE
Primer database

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#24]
Hi,
 
I noticed that when importing the newly designed primers into the Primer database the file extension has to be .txt but the output from the script is a .tsv file. Would it be hard to change the Primer database import to accept .tsv files?
 
Cheers, /Matt

**Comment by aledj2** [comment]
Hi Matt,
Can you point me in the direction of a example tsv file please

**Comment by MattiasJanssonviapath** [comment]
Here you go

**Comment by aledj2** [comment]
sorry doesn't look like the attachment worked. could you send me a link to one, or just stick one in the folder where the script imports primers from


Aled

Aled Jones
Clinical Bioinformatician
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: aledjones@nhs.net
________________________________

**Comment by MattiasJanssonviapath** [comment]
It's now in S:\Genetics\DNA LAB\Primers\MokaPrimerDatabase\primer_designs

**Comment by aledj2** [comment]
thanks, that's been done. it will hopefully be rolled out (along with other primer related things you mentioned last week) in the next few days
