### ISSUE TITLE
"Missing Primers"

### ISSUE THREAD

**Issue by JodieYates** [moka-guys/helpdesk#240]
Hey,

We discovered a few primers today that were not visible to us in MOKA. Aled found they had been set at Null status and that was the reason but we are not sure how this happened! If we can figure it out so we can stop it from happening again that would be great! 

I know you guys are busy so in the mean time I'll try and keep an eye out for any fragment IDs that disappear! :)

**Comment by aledj2** [comment]
Hi Jodie, I have changed the database so status field can't be Null. This should stop the status from being deleted. 
I've also gone through all the forms and ensured that the status can't be changed to Null. 
Still none the wiser to how it occured in the first place.
Thanks
Aled
