### ISSUE TITLE
NCARDS audit

### ISSUE THREAD

**Issue by andyb3** [moka-guys/helpdesk#243]

**Comment by andyb3** [comment]
Talk to Richard about what he did last year

**Comment by andyb3** [comment]
Ask Andrew Marsh if there's problems

**Comment by woook** [comment]
Not a huge priority.

**Comment by woook** [comment]
Ask Andrew March to create a sproc/data extract to provide the necessary normalised dataset from GW, then combine with Moka data. Want to do this once and make it as close to turnkey as possible.

**Comment by NMNS93** [comment]
Awaiting wook chat with Kathy
