### ISSUE TITLE
Backup data from external hard drives

### ISSUE THREAD

**Issue by andyb3** [moka-guys/helpdesk#246]
Backup the nextgene sequencing data on external hard drives to nexus

**Comment by aledj2** [comment]
one project for all harddrives? One Nexus project per HD, one project per NGS run?
Nana's script would make this a breeze

**Comment by andyb3** [comment]
Ask DNA to provide project names. Possibly just everything into one project, with subfolders for each hard drive (Mickey etc.)

**Comment by aledj2** [comment]
Goofy is done

**Comment by aledj2** [comment]
Minnie has been restarted - each file was duplicated in Nexus (not sure how this happened with upload agent)
Mickey has also been restarted, 8 files were missing from Nexus.
Goofy is done

**Comment by aledj2** [comment]
Mickey & Minnie both now complete.
used backup runfolder script to upload.
then commands `dx find data | wc -l` and `find . -type f | wc -l` to count files.
If numbers didn't  match custom python script (attached) used to upload missing files

**Comment by aledj2** [comment]
[mickey_missing_files.py.tar.gz](https://github.com/moka-guys/helpdesk/files/2827822/mickey_missing_files.py.tar.gz)
