### ISSUE TITLE
Add users to Moka citrix AD group

### ISSUE THREAD

**Issue by aledj2** [moka-guys/helpdesk#252]

**Comment by aledj2** [comment]
INC0950376 has been closed and I have been added.

They have said line manager needs to request access for all other users (reassigning to @woook)

**Comment by woook** [comment]
Who am I added to which AD group?

**Comment by aledj2** [comment]
Graeme, nana, Amy (anyone who needs access via citrix )

**Comment by andyb3** [comment]
The AD group is called 'ctxapp – moka'
