### ISSUE TITLE
Moka WES: Can no longer sort by genes column

### ISSUE THREAD

**Issue by SueLillis** [moka-guys/helpdesk#257]
Since the lastest Moka update, we can no longer sort by the gene column when doing WES analysis with Moka.
 
Is this an intentional change ? Is it possible to revert this? 

Thanks
Sue

**Comment by andyb3** [comment]
Hi Sue,

Not sure why that has happened! It's not intentional. Will look into it.

**Comment by andyb3** [comment]
Hi Sue,

Just revisited this.

The genes field in the database previously had a character limit of 50, however this was removed in August following an error when a variant was found in many overlapping genes, exceeding the character limit.

We therefore removed the character limit. Weirdly, it appears that removing this character limit in the database has meant MS Access will no longer sort on this field.

I'll look at putting a (longer) character limit back on this field and hopefully that will fix it!

Thanks,
Andy

**Comment by andyb3** [comment]
Actually might need to change to NVARCHAR(255) so that Access sees it as short text instead of long text

**Comment by andyb3** [comment]
FYI this has been fixed in the new release. Please restart Moka. @hkuoppamaa
