### ISSUE TITLE
WES coverage report

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#26]
Hi guys,

Got a failed coverage report for TestID 624. Need Pan1013 and Pan1479.

Cheers, /Matt

**Comment by aledj2** [comment]
looks like the internal patient ID in the NGSTest table (2136229221) doesn't match the internal patient ID associated with that DNA (2136245497)

**Comment by MattiasJanssonviapath** [comment]
Sorry that doesn't tell me anything. I updated the patient info in Moka, but that didn't make any difference. What do I have to do?

**Comment by aledj2** [comment]
Sorry Matt, that was just a memo for me to look into! will get back to you

**Comment by aledj2** [comment]
Hi Matt, ignore that about the internal patient ID that was a false alarm. It's because the status is complete - if you change the status to something else it should work.

**Comment by MattiasJanssonviapath** [comment]
Hi Aled,

The status is NGS, not Complete. Or which status do you mean?

**Comment by aledj2** [comment]
ok finally this is done. report in usual place (please check)

There was the below message when creating the report:
WARNING:4 genes are present in the gene panel(s) which are not in Pan493 (the exome bed file). These genes will not be present in the coverage report. Please ask the bioinformatics team to identify these genes if required.

Not looked into it but they will likely be phenotype only locus or somthing like that. Please ask if you need more info!
