### ISSUE TITLE
Meeting room bookings link

### ISSUE THREAD

**Issue by sbint** [moka-guys/helpdesk#260]
Please can we get the URL link for the meeting room bookings available through Moka under the "reference" tab.
The URL is:
https://caprica-ext.genetics.kcl.ac.uk/mrbs/week.php?room=8

Thanks

**Comment by aledj2** [comment]
to be added to menu table:
menu_level=2
parent_menu_id=9
name = meeting room booking
action = 473  Meeting Room booking
type = form
AcView = acNormal
Level_sort = 1175

**Comment by aledj2** [comment]
PR issued.
