### ISSUE TITLE
Amendement to footer of PGD report template

### ISSUE THREAD

**Issue by sbint** [moka-guys/helpdesk#261]
URGENT:
Please can you amend the footer of the PGD report templates so the platform information at the end reads:
Array platform: Agilent design 085030. Genome build hg19/GRCh37. Median resolution on genomic DNA 120kb. Detection of regions <5Mb is dependent on location of imbalance.

(We lost marks for this in our last CEQAS round)

Thank you

**Comment by aledj2** [comment]
changes made in S:\Genetics_Data2\Moka_dev\aled_dev. These text boxes aren't part of version control process so will get Sue to approve before release

**Comment by aledj2** [comment]
Has been approved and tested in the dev copy of Moka. Awaiting release
