### ISSUE TITLE
Isabelle's initials to go into Moka

### ISSUE THREAD

**Issue by mikecoldwell** [moka-guys/helpdesk#263]
Isabelle's initials (IN) need to go into moka. While editing the list, if it is not any more work, there are loads of excess names of people who no longer work here which could be removed.

**Comment by aledj2** [comment]
Thanks Mike. Have added Isabelle
We have de-activated a number of people recently but perhaps this 'active' filter is not applied on the drop downs. It won't be a priority but if you want you could you raise a separate ticket listing drop downs that aren't filtered
