### ISSUE TITLE
OnePGT - NextSeq 550 data upload to Alissa

### ISSUE THREAD

**Issue by hhewitson** [moka-guys/helpdesk#268]
Hi Heema

Could I ask you to raise an issue at https://github.com/moka-guys/helpdesk/issues 

Just this last message will be enough to action it.

Thanks,

Wook
________________________________________
From: Hewitson Heema (Nee Patel) <Heema.Patel@viapath.co.uk>
Sent: 22 August 2018 12:15
To: AHN, JooWook (GUY'S AND ST THOMAS' NHS FOUNDATION TRUST)
Cc: Gonzalez Justo
Subject: RE: Advice - library pools 
 
Hi Wook, 
 
We did our first NextSeq run on Monday (Pool 1: samples have been anonymised so are 1-24) and Lina said the stats look OK. We have someone from Agilent coming on Thursday 30th Aug to show us the Alissa analysis software so will it be possible to demultiplex and upload the merged FASTQ files before his visit?
 
Heema

**Comment by andyb3** [comment]
FASTQs have been uploaded
