### ISSUE TITLE
Moka XP disappeared

### ISSUE THREAD

**Issue by hkuoppamaa** [moka-guys/helpdesk#270]
As I work remotely I usually access Moka in this folder (esp. if Connect doesn't work): \\gstt.local\shared\Genetics_Data2\Array\Moka_XP but couldn't locate it today. Has it been moved/removed? I would still like to have access to this version of Moka if possible.

Thanks,
Heidi

**Comment by andyb3** [comment]
Hi Heidi,

I'm not sure why you can't access the folder, however the XP version is now very out of date and shouldn't be used anymore. Are you still having problems with your Windows 10 trust laptop?

Thanks,
Andy

**Comment by hkuoppamaa** [comment]
Hi Andy,

We've given up on the laptop as nothing we tried helped. David has just ordered me a new one.

Thanks,
Heidi

**Comment by andyb3** [comment]
Ah OK. Can you use Citrix in the meantime until the new laptop arrives?

**Comment by hkuoppamaa** [comment]
Yes, can use Citrix.
