### ISSUE TITLE
Quick change request. Retire item in "CNV / Confirmation" field

### ISSUE THREAD

**Issue by mikecoldwell** [moka-guys/helpdesk#273]
Hopefully this one is really easy. 
On the "Array results page"  in the "CNV / Confirmation" field there is a item on the list called "Inconsistent region (for new array design)". This is obsolete because the new array design it refers to is now an old array design. Because this option is the first one which comes up when you type inconsistent it just slows us down. 

Thank you very much

Mike

**Comment by aledj2** [comment]
done. Aled
