### ISSUE TITLE
WES - Sorting in Moka

### ISSUE THREAD

**Issue by hkuoppamaa** [moka-guys/helpdesk#276]
Hi,

Would it be possible to re-enable variant sorting by gene and panel name in Moka please?

Thanks,
Heidi

**Comment by aledj2** [comment]
Hi Heidi,

Sue also raised this a while ago (#257 ). We're looking into it and not sure why we can't do that sorting anymore. Can you sort variants on the just panel name alone?

**Comment by hkuoppamaa** [comment]
Hi Aled,

Nope, sorting by panel name alone doesn't work either.

**Comment by andyb3** [comment]
Duplicate of https://github.com/moka-guys/helpdesk/issues/257
