### ISSUE TITLE
Review variants in 100K cancer BAM file

### ISSUE THREAD

**Issue by aledj2** [moka-guys/helpdesk#281]
Could you have a look at 212200514 Bam file

TP53 | 17:7676152 CG>C | ENST00000269305 | c.216delC | frameshift_variant | - \| - | 0.49 (LOH) | 43/88
-- | -- | -- | -- | -- | -- | -- | --

TP53 | 17:7676155 G>A | ENST00000269305 | c.214C>T p.(Pro72Ser) | missense_variant | - \| 0.00 | 0.49 (LOH) | 45/92 |  
-- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by aledj2** [comment]
pleas email Mikel @ m.valganon@nhs.net

**Comment by aledj2** [comment]
TP53 | 17:7676152 CG>C | ENST00000269305 | c.216delC | frameshift_variant | - \| - | 0.49 (LOH) | 43/88 | COSM4336302COSM18569COSM1268331COSM1268332COSM2745091 | Trial (fallopian tube ca, ovarian ca, prim peritoneal ca) Trial (ovarian ca) Trial (ovarian serous ca) | Trial (NSC lung ca, SCLC, breast ca, ca) Trial (NSC lung ca, breast ca, colorectal ca, esophageal SCC, head neck SCC, ovarian ca, pancreatic ca, urothelial ca) Trial (NSC lung ca, ca, colorectal ca, head neck SCC, ovarian ca, prostate ca) | both
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
TP53 | 17:7676155 G>A | ENST00000269305 | c.214C>T p.(Pro72Ser) | missense_variant | - \| 0.00 | 0.49 (LOH) | 45/92 | COSM44018COSM4070066COSM4070067COSM4070068COSM4070069 | Trial (NSC lung ca, SCLC, breast ca, ca) Trial (NSC lung ca, breast ca, colorectal ca, esophageal SCC, head neck SCC, ovarian ca, pancreatic ca, urothelial ca) Trial (NSC lung ca, ca, colorectal ca, head neck SCC, ovarian ca, prostate ca) Trial (fallopian tube ca, ovarian ca, prim peritoneal ca) Trial (ovarian ca) Trial (ovarian serous ca) |   | both

**Comment by andyb3** [comment]
Discussed with Mikel
