### ISSUE TITLE
Moka looks odd

### ISSUE THREAD

**Issue by hkuoppamaa** [moka-guys/helpdesk#285]
Hi,

I am currently using Citrix to access Moka as it doesn't work on the laptop that was sent to me. It's been ok so far but this morning it looked odd (see picture) and I can't do anything in Moka. I have tried logging in and out of Citrix and launching Moka again a few times but it still looks the same. Any idea what might be going on?

![moka](https://user-images.githubusercontent.com/31348002/45290875-4c9cc900-b4f9-11e8-84ea-dc521a5fe686.JPG)

**Comment by hkuoppamaa** [comment]
Hi Andy,

I've just tried this and an updated version of Moka was retrieved. However, it didn't fix my problem :/ Any other ideas?

Thanks,
Heidi

**Comment by hkuoppamaa** [comment]
I tried logging out and in once again an now it looks normal! I'll let you know if the problem returns.

Thanks!

**Comment by andyb3** [comment]
Great, glad it's sorted!
