### ISSUE TITLE
Buy new switch for dual monitors, keyboard & mouse

### ISSUE THREAD

**Issue by Graeme-Smith** [moka-guys/helpdesk#294]

**Comment by woook** [comment]
For something suitable on amazon and order.

**Comment by Graeme-Smith** [comment]
ATEN CS22U 2-Port USB Cable KVM Switch
https://www.amazon.co.uk/ATEN-CS22U-2-Port-Cable-Switch/dp/B002NTIZCG/ref=sr_1_3?ie=UTF8&qid=1537862523&sr=8-3&keywords=kvm+switch

Active HDMI to VGA Adapter with Audio, Benfei HDMI to VGA Converter Gold-Plated Cord
https://www.amazon.co.uk/Active-Adapter-Benfei-Converter-Gold-Plated/dp/B01KLKQN9U/ref=sr_1_2_sspa?s=computers&ie=UTF8&qid=1537862853&sr=1-2-spons&keywords=vga+to+hdmi&psc=1

**Comment by NMNS93** [comment]
Try fitting Nana and Graeme along office desk. If this works consider also ordering laptop docs.

**Comment by Graeme-Smith** [comment]
Requirements:
x2 VGA to display port adaptor
https://www.amazon.co.uk/Rankie-DisplayPort-Adapter-1080P-Coverter-Black/dp/B00Z08TZNU/ref=sr_1_3?s=computers&ie=UTF8&qid=1540458262&sr=1-3&keywords=vga+to+displayport

ATEN CS22U 2-Port USB Cable KVM Switch
https://www.amazon.co.uk/ATEN-CS22U-2-Port-Cable-Switch/dp/B002NTIZCG/ref=sr_1_3?ie=UTF8&qid=1537862523&sr=8-3&keywords=kvm+switch

x1 Standard adjustable office chair

x1 Windows 10 Trust Machine (M. Yau may have a spare test machine we can use)

**Comment by Graeme-Smith** [comment]
Order has been placed with IT - awaiting delivery.
