### ISSUE TITLE
PanelApp genes for new custom exome

### ISSUE THREAD

**Issue by andyb3** [moka-guys/helpdesk#298]
Michael wants to request a new focused exome design that contains all the panelapp green genes. 

For this he needs a list of gene symbols from PanelApp.

He has a meeting about this on 26th so ideally provide the list before then.

**Comment by andyb3** [comment]
Since some amber and red genes are likely to be upgraded to green in the future, possibly might also be worth pulling out a list of all panelapp genes to see how this compares to green only?

However need to be aware that adding more genes could push into a higher price bracket, and will mean fewer samples can be multiplexed.

**Comment by andyb3** [comment]
PanelApp panels in Moka were recently updated, so could probably use a Moka query to get the gene lists.

**Comment by andyb3** [comment]
Check audits and projects, Aled already done something with this

**Comment by NMNS93** [comment]
Waiting till Aled gets back.

**Comment by andyb3** [comment]
Michael says Agilent already have a list of the genes
