### ISSUE TITLE
Old Runs on Work Station

### ISSUE THREAD

**Issue by Graeme-Smith** [moka-guys/helpdesk#299]
There are several old runs still on the work station (520 Gb) - can we go through the list below at a Bioinformatics meeting and decide which can be deleted.

https://docs.google.com/spreadsheets/d/1VJvGUuw3CqsMvlQrV1_NMbsT-EkpKdECcihcTeVyEjw/edit?usp=sharing

**Comment by NMNS93** [comment]
Waiting till Aled gets back.

**Comment by aledj2** [comment]
Have added the status of each old project to the spreadsheet

**Comment by Graeme-Smith** [comment]
Nana - Update backup script + then use on old runs and delete from workstation

**Comment by NMNS93** [comment]
1. Change upload script to upload everything (dev + production files)
2. Automatically delete runs older than 1 week

**Comment by aledj2** [comment]
backup script complete. has it been run on all folders? Can we delete the old run folders?
Script to perform check and delete in development

**Comment by andyb3** [comment]
Any code used to do the checks eg that in the bashrc needs to be code reviewed
