### ISSUE TITLE
Add Nana and Graeme to Lastpass

### ISSUE THREAD

**Issue by NMNS93** [moka-guys/helpdesk#301]
Please.

**Comment by NMNS93** [comment]
Nana and Graeme to slack andy usernames

**Comment by NMNS93** [comment]
Andy can't add. Can we either have a single shared account or pay for premium?

**Comment by andyb3** [comment]
Aled to make new shared Moka folder

**Comment by aledj2** [comment]
awaiting Wook's lastpass email
