### ISSUE TITLE
Automate MultiQC upload

### ISSUE THREAD

**Issue by NMNS93** [moka-guys/helpdesk#307]

**Comment by NMNS93** [comment]
See if PC keys let an app connect to the genomics server.

**Comment by andyb3** [comment]
Code review

**Comment by NMNS93** [comment]
Plan to make multiqc workflow for pipelines

**Comment by NMNS93** [comment]
Note: fail app if report found on server

**Comment by andyb3** [comment]
make sure using docker hash rather than version tag - store as asset in Nexus
