### ISSUE TITLE
WES: Urgent, unable to launch Moka

### ISSUE THREAD

**Issue by hkuoppamaa** [moka-guys/helpdesk#31]
It seems that remote workers have lost access to Moka (at least me and Rachael I).  The first step ("Please select your level of Moka access") works fine but then I get a window pop up saying "Microsoft Office Access has encountered a problem and needs  to close" and then it just crashes. Might this be due to an update? Us remote workers still use Windows 2003. I was able to use Moka normally until I got back from lunch today and tried to launch it again. Rachael has had this issue the whole day but she logged in after me. Please help!

**Comment by andyb3** [comment]
OK Moka was updated this morning using a Windows 10 machine and it's clearly stopped it from working on older versions of Windows. As a workaround I will create a separate copy that should work for you. Will let you know when this is done.

**Comment by andyb3** [comment]
FYI this is only intended as a short term workaround. I have just sent an email enquiring when you will be upgraded to use Citrix (the FWA replacement).

**Comment by hkuoppamaa** [comment]
The file works! Is this how I should lauch Moka for now?

**Comment by andyb3** [comment]
OK I've given you each your own copy in `\\gstt.local\shared\Genetics_Data2\Array\Moka_XP\`
Use these for now. Be aware that these copies won't receive updates so they should only be used in the short term.

**Comment by andyb3** [comment]
Hi Heidi, just so you know we are still trying to get Moka rolled out to Citrix. Sorry it's taking awhile. Hopefully this will be sorted soon.
