### ISSUE TITLE
Possibly Urgent! WES extension to scope gene list

### ISSUE THREAD

**Issue by andyb3** [moka-guys/helpdesk#310]
Jerry asked for the ETS WES gene list. Apparently we have to do this monthly now? Check with Wook though before doing anything in case it's not required.

There is a query in Moka https://github.com/woook/moka-fe/blob/master/queries/s_WESReportedGenes
However if I remember rightly in its current form it can produce duplicate entries if the same gene has been authorised by different people. 
Also I think UKAS just want a list of 'new' genes (not previously validated). So results might need to manual curation in Excel until we update the query and store results in a table.

**Comment by aledj2** [comment]
Jerry has chased this - said mid next week would be ok.

**Comment by aledj2** [comment]
Updated gene list in \\gstt.local\shared\Genetics\DNA LAB\Current\WES\181023_UKAS_flex_scope_gene_list.xlsx

**Comment by aledj2** [comment]
Updated Query in moka (s_WESReportedGenes_181023)

**Comment by aledj2** [comment]
Longer term suggestion:Create table with

**Comment by NMNS93** [comment]
Wook: Use query as it is (don't take out duplicates) and send to UKAS

**Comment by NMNS93** [comment]
Aim to be done by close of Monday

**Comment by NMNS93** [comment]
Done. There is a new menu button under NGS titled 'Report WES Gene list for UKAS'. Double-clicking this calls the query s_WESReportedGenes. Queries used below (second was to correct error):

insert into dbo.Menu(Menu_Level,Parent_MenuID,Name,Action,Type,AcView,Level_Sort) values (2,10,'Report WES Gene list for UKAS**','s_WESReportedGenes_181023','Query','acViewNormal',1371)

update dbo.Menu set Action="s_WESReportedGenes" where dbo.Menu.MenuID=218
