### ISSUE TITLE
Primer edit

### ISSUE THREAD

**Issue by JodieYates** [moka-guys/helpdesk#318]
Hey,

can we edit the name of primer:
2765 | NERD_ERCC2_ex9_10_v1_Legacy 

to state: 
2765 | NERD_ERCC2_ex10_11_v1_Legacy

This will match the tube and be consistent with the other comments in the NERD primers.

Also can we change the name of:
3535 | DMD_MPZ2_Legacy

to 
3535 | MPZ_247bp_v1_Legacy  

Thanks

**Comment by andyb3** [comment]
Hi Jodie,

For primer 2765 the TestResultNotes say 'amplifies ex9_10'.  Does that also need updating?

Thanks,
Andy

**Comment by JodieYates** [comment]
Hey,

Nope, the note is correct. 

The name on the tube 10_11 but it does actually amplify 9_10, Jo wanted the name in MOKA to match the tube hence the change of name. 

Thanks 

Jodie

**Comment by andyb3** [comment]
OK that's all done! Please check it looks correct now

**Comment by JodieYates** [comment]
All looks fine.

Thanks :)
