### ISSUE TITLE
Runsheet automation

### ISSUE THREAD

**Issue by adelecorrigan** [moka-guys/helpdesk#32]
The autofill option for array sub numbers is no longer working. Please can we fix this and also automate the steps of assigning a specimen to the patients and assigning the patients to an array. Thanks!

**Comment by woook** [comment]
This is not huge but isn't a quickfix. Probably needs a requirements doc or at least some user research to figure what needs to be done.

**Comment by schuiie** [comment]
Wook said to make this urgent. Thanks guys. :)

**Comment by woook** [comment]
Part of #30
