### ISSUE TITLE
New Ingenuity User

### ISSUE THREAD

**Issue by SueLillis** [moka-guys/helpdesk#324]
Hi Alex / Andy

Please can you create an individual Ingenuity a/c for our  new starter?
User name: maha.younes@viapath.co.uk 

Maha will be working on WES for now.

Thanks
Sue

**Comment by NMNS93** [comment]
Hi Sue,

Maya should now have an E-mail to complete the process.

-Nana

**Comment by SueLillis** [comment]
Thanks Nana for doing this so quickly!
Sue
