### ISSUE TITLE
Automate input of charges for GeL negs

### ISSUE THREAD

**Issue by andyb3** [moka-guys/helpdesk#329]
S:\Genetics_Data2\Array\Audits and Projects\181030_GW_cost_stored_procedure

**Comment by andyb3** [comment]
speak to Anifa re booking in of GEL samples to GW

**Comment by aledj2** [comment]
Checked if logic for identifying correct sample is  correct (awaiting reply)
Code is pretty much done, needs a little more testing.

**Comment by andyb3** [comment]
Hi Andy,
For 99% all of the RD samples the disorder of ‘Whole Genome Sequencing’, a Test Description of ‘GeL’, and an associated DNA number is automatically  added once the sample is checked into our lab daybook on GW.
However there are a few cases where these details are added manually and the test description of ‘GeL’ is missing but the other details mentioned above should be there.
Majority of the patients should have one GEL sample for RD but there are cases when the first sample has failed and we have a second sample, so two DNA numbers with 100k requests.
Some of the 100k samples will have other  test requests added to them i.e export DNA, not sure if that makes any difference to you.
Other than that I don’t see any issues.

Regards,
Anifa

From: Bond Andrew 
Sent: 13 November 2018 09:10
To: Pereira Anifa <Anifa.Pereira@gstt.nhs.uk>
Subject: GeL Geneworks Question

Hi Anifa,

I’m currently working on an automated solution for reporting negative GeL cases. As part of this I’m trying to automate the step that adds a charge into Geneworks. 

The charge has to be raised against a specific specimen and test. I therefore need to find an automated way to find the correct specimen ID and test ID to raise the charge against. To do this I am selecting for samples that have a geneworks disorder of ‘Whole Genome Sequencing’, a TestDescription of ‘GeL’, and an associated DNA number. In the samples I have tried this just returns one result, the GeL blood sample that was extracted. However I don’t know much about how the GeL samples are booked into geneworks, so I wanted to check with you if my logic sounds OK?? Are there any situations where this logic might fall down? E.g. Where there are multiple GeL samples with a DNA number etc.

Many thanks,
Andy
