### ISSUE TITLE
primer edit 

### ISSUE THREAD

**Issue by JodieYates** [moka-guys/helpdesk#332]
Hey, 

I need to swap some primer names. So currently they are in MOKA as: 

> Fragment ID | Amplicon Name
> 3268 | ALS_TARDBP_Ex06_1_v2_Legacy
> 3269 | ALS_TARDBP_Ex06_2_v3_Legacy
> 3270 | ALS_TARDBP_Ex06_1_v1F_Ex06_2_v2R_Legacy

But I need them changed to (sequences stated for checking/your peace of mind!): 

> Fragment ID | Amplicon Name
> 3268 | ALS_TARDBP_Ex06_1_v1F_Ex06_2_v2R_Legacy
> (tgcttatttttcctctggctttag | ACTCCACACTGAACAAACCA)
> 
> 3269 | ALS_TARDBP_Ex06_1_v2_Legacy
> (TTTAGATAAATTAATGCTTGTAAT | CTCTGCATGTTGCCTTGGT)
> 
> 3270 | ALS_TARDBP_Ex06_2_v3_Legacy
> (TGCCGCCCAGGCAGCACTA | AAATATTACAGGAGAAACCTTT)

Thanks

Jodie

**Comment by aledj2** [comment]
done, please check

**Comment by JodieYates** [comment]
That was super quick! All seems fine. 

Thanks :)
