### ISSUE TITLE
Unable to open MOKA

### ISSUE THREAD

**Issue by JodieYates** [moka-guys/helpdesk#334]
Hey,

So only Karishma and Amanda seem to be having issues with opening MOKA.

There login names are KGohil1 and ARoper. 

Thanks

Jodie

**Comment by andyb3** [comment]
Thanks Jodie. Wook will request that they are added to the necessary AD groups.

**Comment by JodieYates** [comment]
Hey,

Sophia has said she is also having the same issue, her login name is sguarniere

Thanks

**Comment by woook** [comment]
IT have actioned this now so should be able to use Moka.
Please note that users are unable to use Moka without going through this step.
