### ISSUE TITLE
QIAGEN IVA new charge

### ISSUE THREAD

**Issue by aledj2** [moka-guys/helpdesk#335]
Felicity reported that sharing samples from the generic account to individual accounts prompts a message box asking to accept the associated charges.

Have asked for screenshots and more detailed instructions of the process which caused this.

**Comment by felicity-lapper** [comment]
I shared 25 samples from the generic account to my personal account.  When I logged into my account the "Review shared samples" pop up appeared as normal, then when I clicked Import the message box appeared - see the attached screenshot.

![ingenuity screenshot](https://user-images.githubusercontent.com/33058068/47792516-19660180-dd14-11e8-91a3-29d8e0ae4ce5.PNG)

Thanks for looking into this.

**Comment by aledj2** [comment]
We get the same message, have sent an email to Ingenuity support. If there are any urgent cases to be shared we can re-submit them directly into a user account.

**Comment by aledj2** [comment]
I'm closing this issue - despite the messages the contract hasn't changed but may in the future. Is being assessed by Viapath
