### ISSUE TITLE
WES - failure to create coverage report

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#339]
Hi guys,

I cannot create the coverage report for TestID 2517, Pan 2538

See attached error message.

Cheers, Matt

**Comment by andyb3** [comment]
Hi Matt,

Found the problem, should be fixed now.

![image](https://user-images.githubusercontent.com/20341309/47918916-dc317900-dea5-11e8-8cf7-842e4be39237.png)

**Comment by MattiasJanssonviapath** [comment]
Cheers Andy
