### ISSUE TITLE
List of variants for Ingenuity Verification

### ISSUE THREAD

**Issue by rachaelmein** [moka-guys/helpdesk#342]
I have generated a list of variants that I would like to load into Ingenuity.  I would like to use this list of variants to verify new updates of Ingenuity (similar to how the WES team do it).  Are you able to convert this list into a format that can be uploaded to Ingenuity?
The list of variants is saved here;
P:\DNA LAB\Current\NGS worksheets\Ingenuity Panel Lists\Ingenuitys verification variants

Many thanks
Rachael

**Comment by aledj2** [comment]
Hi Rachael, 
We're missing information from some of the variants to create these files.
Would it be possible to provide for each variant the sample name (eg NGS215B_36_153071_VK_F_CMCMD_Pan1464)
Thanks
Aled

**Comment by rachaelmein** [comment]
Hi Aled

What information do you need?  The problem is for the ones that a single sample is not listed (ie the ones that end in predicted deleterious) I got the variants from a batch analysis and therefore it will take me ages to go back to them to find out which sample it is on.  I don’t want all variants for these samples I just want the variants I listed.  I only put the analysis ID in the table for my records I didn’t think you would need this.  What information does ingenuity need for it to be imported?  I thought this could be done with non real data (ie. not from a VCF of seq data which include all  variants).

I’m working from home today but it may be easier to discuss this face to face tomorrow to make sure we both understand what is needed and required here.

Thanks very much

Rachael

**Comment by aledj2** [comment]
Ingenuity requires a VCF and to create this VCF we need the REF and ALT which is different to the HGVS provided in the spreadsheet. We'd also need to provide all the fields that Ingenuity uses to filter (eg QC).

Therefore, we thought the easiest approach would be to download all the VCF files from the samples and write a script to pull out the specified variants from each file.

We may be able to find the VCF files with slightly less information than the full sample name, could you provide any of the following?
DNA number
Initials
NGS run (eg NGS219A)

**Comment by rachaelmein** [comment]
To get DNA number and initials of specific samples I would have to go back into all of the runs.  I could give you that information for the entire batch regardless of whether they have variant of interest or not.  Then if you create a script to pull out specific variants it would just ignore those samples.  Would that help?

Sorry this is proving more difficult than I envisaged.  Sue had said some time ago that you could manually input a variant into ingenuity without any associated data so I thought this would be similar to how she did that.

Thanks
Rachael

**Comment by aledj2** [comment]
I guess we could looking through all the samples on a run for each variant. Would any variant be present in multiple samples on a run?
We'd still need a sample or run name for for the last two variants in the list.

**Comment by woook** [comment]
How many variants is in this list?

**Comment by woook** [comment]
Can we feed the HGVS through mutalyzer?

________________________________

**Comment by aledj2** [comment]
Hi Rachael, 

Would it be ok for all the variants to have the same/artificial data in the VCF, eg homozygous and call quality of 1000?  (as per the WES VCF)

Would it be possible to provide the variants in a mutalyzer friendly format (transcript:HGVS).

Thanks,
Aled

**Comment by rachaelmein** [comment]
Dear Aled

Yes all variants can have same artificial data in VCF.  I have added a tab onto the excel file with variants in transcript:HGVS format
P:\DNA LAB\Current\NGS worksheets\Ingenuity Panel Lists\Ingenuitys verification variants

Thanks very much

Rachael

**Comment by aledj2** [comment]
Hi Rachael,
I have the following errors when converting HGVS to chromosomal positions:
NM_000152.4 could not be found - NM_000152.3 was suggested as an alternative
NM_014625.3 could not be found - NM_014625.2 was suggested as an alternative
NM_022068.3  could not be found - NM_022068.2 was suggested as an alternative
NM_001267550.2 could not be found - NM_001267550.1 was suggested as an alternative 

Line 88 had two HGVS descriptions, I assume the red one is the one to take?

**Comment by rachaelmein** [comment]
Those alternative transcript are fine. I must have missed the double entry on line 88.  Yes the red one is correct.

Thanks very much.
Rachael

**Comment by aledj2** [comment]
Hi Rachael, I have shared an Ingenuity analysis with you. How does it look?

**Comment by rachaelmein** [comment]
Thanks Aled
It look good.  All is present except for this one variant
10

16943450

CUBN

NM_001081.3

c.8071G>A

p.G2691R

NM_001081.3:c.8071G>A


I think you have put it in as chr1 instead of 10 as there is an extra variant.

Thanks very much for this.

Rachael

**Comment by aledj2** [comment]
Have shared an updated analysis

**Comment by aledj2** [comment]
Hi Rachael, have you had a chance to look at this updated analysis? Do you need the vcf or are you just going to reanalyse the sample in ingenuity?

**Comment by rachaelmein** [comment]
Dear Aled

Sorry only just looked at the updated analysis. I will just use what you have sent me in Ingenuity so no need for anything further.  Thanks so much for this, it’s a great help.

Cheers
Rachael

**Comment by aledj2** [comment]
Sample will be kept in Ingenuity. The original VCF can be found @ S:\Genetics_Data2\Array\Audits and Projects\181204_custompanel_ingenuity_verification
