### ISSUE TITLE
DNAnexus access

### ISSUE THREAD

**Issue by mneat** [moka-guys/helpdesk#344]
The issue with access to DNAnexus is now constant and chronic; having previously been intermittant I have been unable to get onto nexus all this week. This means we can't analyse our Swift cases without resorting a very slow and clunky workaround using the Viapath cloud - this is a clinical risk e.g I have a case on tomorrows run that needs to be reported before 9am - if I can't get on to nexus then this patients treatment will be delayed.

**Comment by aledj2** [comment]
Hi Michael. 
We've started using service now for issues like this. Can you re-raise this ticket there (I'll resend instructions how to do this). This will allow me to reference this ticket when escalating my ticket with IT. 
I've raised a second ticket with IT describing this problem and asking what thier solution would be.

**Comment by mneat** [comment]
Just doing this – what is ‘site affected’? – It won’t accept Guy’s or GSTT

**Comment by aledj2** [comment]
I think it's "GUYS"?


Aled

Aled Jones
Clinical Bioinformatician
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: aledjones@nhs.net
________________________________

**Comment by aledj2** [comment]
closing this issue as it's now in service now (INC0028158)
