### ISSUE TITLE
Coverage report error NGS Test ID 2699

### ISSUE THREAD

**Issue by RachaelIrwinViapath** [moka-guys/helpdesk#346]
Hi, I'm trying to create a coverage report for WES case NGS Test ID 2699 (PRU 468394:01, DNA 204033), but I keep getting a stream of error messages. It just needs to include the Primary panel (Pan2630). Please could you investigate/create the coverage report? The case is otherwise ready to report, so hoping to get it out before the end of the month. Thanks very much! Rachael.

**Comment by Graeme-Smith** [comment]
Hi Rachel - can you please raise this as an issue on Service Now. The issues on this GitHub repo are no longer regularly reviewed.

**Comment by RachaelIrwinViapath** [comment]
Hi Graeme,

Sorry, I didn’t realise (and I’ve just logged two things). Do you mean I should instead raise on https://viapath.service-now.com?

Thanks,
Rachael

**Comment by andyb3** [comment]
Hi Rachael,

Yes please, and make sure you select 'Genome Support' as the Affected Service when you raise the tickets

**Comment by Graeme-Smith** [comment]
Hi Rachel,

Yes, if you could please raise it on https://viapath.service-now.com, you should be able to allocate it to the Genome Informatics team which will assign it to us.  From there I can assign the task to a member of the bioinformatics team.

Regards,

Graeme

________________________________

**Comment by RachaelIrwinViapath** [comment]
Thanks Graeme - both issues should now be logged on Service Now (ref. INC0031205 and INC0031206).

Cheers,
Rachael
