### ISSUE TITLE
BAM file request NGS Test ID 2001

### ISSUE THREAD

**Issue by RachaelIrwinViapath** [moka-guys/helpdesk#347]
Hi,

We have had a request from GOSH to send them the BAM file for one of our WES patients (NGS Test ID 2001, PRU 431689:02, DNA 195546) so that they can look at another gene that wasn't covered in the original WES request (it's a Complete case). I offered that we could do a re-analysis, but they would like the BAM. Could you organise to send it to them please? The recipient is Gavin.Arno@gosh.nhs.uk (their ref. 849949), I've saved all communication under test files on Moka (my email contact has been with eleanor.hay@nhs.net). Could you please also let them know if there is a cost associated with us sending them the file?

Thanks very much,
Rachael

**Comment by Graeme-Smith** [comment]
Hi Rachel - can you please raise this as an issue on Service Now. The issues on this GitHub repo are no longer regularly reviewed.
