### ISSUE TITLE
Primer database

### ISSUE THREAD

**Issue by anmolen** [moka-guys/helpdesk#39]
In primer test results there is no primer sequence. Where can I find primer sequence before primer pair approval.

**Comment by aledj2** [comment]
Hi Aneta,

I discussed this with Matt and Sue and they have said they do not want the forms we discussed last week. Matt said he is happy to discuss this with you.

I think I said I'd forward the location of the forms produced by the database that are submitted for ordering the primers - these are S:\Genetics\DNA LAB\Primers\MokaPrimerDatabase\ordersheets

These hold the primername (eg gene/exon), the sequence and the amplicon ID (number)
