### ISSUE TITLE
WES - Moka links to R&D folder

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#41]
Hi guys,

As discussed in the meeting today we are moving WES from R&D to Current, and some resources in Moka links to the R&D folder, and need to be updated.

Exported panels: Moka panels are currently exported to S:\Genetics\DNA LAB\R&D\New Tests\WES\Ingenuity\Moka Panels when double-clicking a PanelCode in the NGS Panels page. New location for exported panels is S:\Genetics\DNA LAB\Current\WES\Panels\Moka Panels
If this update could be tied together with implementing exporting through double-clicking a PanelCode in the WES Results page that would be great.

Coverage Reports: These are currently exported to S:\Genetics\DNA LAB\R&D\New Tests\WES\Results\Coverage reports
Please change this location to S:\Genetics\DNA LAB\Current\WES\Coverage reports

Cheers, /Matt and Sue

**Comment by andyb3** [comment]
Links have all been updated
