### ISSUE TITLE
WES - Request re-runs

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#45]
Hi guys,

We cannot set test status to 'Test Failed' for a test that failed Data Processing QC and needs to be re-run under a different TestID. 
1. We need a new TestID to be accreditation compliant and avoid issues with several sequencing files associated with the same TestID and then trouble making coverage reports.
2. We cannot currently re-order a case - workaround is to go into the patient page and change the status from 'NGS' to 'Complete'.
3. Workaround leaves an 'old' test sitting and cluttering up the Dashboard with a 'Data Processing QC Failed' status.

What we need:
1. We need to be able to change a status from 'Data Processing QC Failed' to 'Test Failed' and for this change to enable us to re-order a test through 'Order Exome Test'.
2. A case with 'Test Failed' status to be hidden from the Dashboard just like a 'Complete' case is.
Optional extra:
3. Able to link tests or mark them as re-runs so they are easier to find.

Cheers, /Matt

**Comment by aledj2** [comment]
Hi Matt, 
Can I check you're happy to be able to change the status to test failed without any authorisation?
Aled

**Comment by MattiasJanssonviapath** [comment]
Hi Aled,

Yes, I’m happy with that.

Cheers, /Matt

**Comment by aledj2** [comment]
A Moka release which allows the status to be changed to test failed on the results page. Any samples with this status are then hidden form the dashboard.

Does this solve this issue?

Aled

**Comment by MattiasJanssonviapath** [comment]
Hi Aled,

I changed the status for these cases from ‘Data processing QC failed’ to ‘Test failed’ so that worked. It didn’t change the status in the patient page from ‘NGS’ to ‘Completed’ though. This is needed for us to be able to make a new request on the same patient.

Cheers,

/Matt
