### ISSUE TITLE
Importing into MOKA

### ISSUE THREAD

**Issue by laurenpitt** [moka-guys/helpdesk#58]
I am unable to import my VCF file into Moka. Could you please check my permissions to see if I am restricted for anything. Thanks

**Comment by andyb3** [comment]
Need to request access to the following folder: S:\Genetics_Data2\Array\Software\Python
https://gstt.service-now.com/

**Comment by aledj2** [comment]
May also be worth asking for Irena at the same time.


Aled

Aled Jones
Clinical Bioinformatician
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: aledjones@nhs.net
________________________________

**Comment by laurenpitt** [comment]
She had a look and can open the folder so I assume she will be able to import into Moka.

I think I am in the right place, but it says something about needing to be a manager to submit the form.

**Comment by laurenpitt** [comment]
Does Wook need to request the access?

**Comment by aledj2** [comment]
Irina to request access
