### ISSUE TITLE
WES - coverage report failed

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#59]
Hi guys,

TestID 690, panels Pan1084, Pan345
Mismatched number of genes.

Cheers, /Matt

**Comment by aledj2** [comment]
A fix to address cases like this was made a while back but needs code review. Will let you know when it's fixed

**Comment by aledj2** [comment]
OK, the fix has been rolled out. Can you try again now please

**Comment by MattiasJanssonviapath** [comment]
Yep, that worked! 
Cheers /Matt
