### ISSUE TITLE
WES - coverage report on old data

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#60]
Hi guys,

I think the overage report I could generate used data from old failed run.
Coverage report for testID570, on panel Pan898, Pan899, Pan1587
Use new QXT run in 171013_NB551068_0070_AHTGT2BGX3_NGS187C_WES18 please.

Cheers, /Matt

**Comment by aledj2** [comment]
S:\Genetics\DNA LAB\R&D\New Tests\WES\Results\Coverage reports
