### ISSUE TITLE
WES - coverage report on old data

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#61]
Hi guys,

Another one where it generate coverage using data from old failed run.
 Coverage report for testID298, on panel Pan520
Use data from 170526_NB551068_0048_AHLFFGBGX2_NGS169A please.

Cheers, /Matt

**Comment by aledj2** [comment]
Done, please see S:\Genetics\DNA LAB\R&D\New Tests\WES\Results\Coverage reports
