### ISSUE TITLE
WES - New ACMG comments page quality of life changes

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#65]
Hi guys,

A couple of things I noticed with the new ACMG comments page;
1. The 'active' location is not the comments box but rather the first tickbox, which means we have to first click in the comments box before we can start typing - change to have the comments box 'active' when opening, please.

2. When starting to type in the comments box, the whole page jumps so you can no longer see the 'Close' button. Even with a short comment this means we have to scroll up to show the 'close' button and exit the page. This also hides 'Patient Details' and 'Variant' from view. Change the top part with  'Patient Details', 'Variant' and 'Close' button to always be visible, please.

3. Can the 'Variant' information box also include which gene, and if possible c. and p. info?

Cheers, /Matt

**Comment by andyb3** [comment]
Yes that all sounds doable

**Comment by andyb3** [comment]
Done
