### ISSUE TITLE
URGENT!!!! Charts required for ISO competency audits

### ISSUE THREAD

**Issue by schuiie** [moka-guys/helpdesk#68]
Hello,

We have had to change our competency reassessments due to an ISO requirement. This will require pulling information on who did what and when out of Moka.

Please can we have charts similar to the the checking chart under the array menu showing monthly breakdown of the numbers for each member of staff for a given task to include checking normal results (excluding PGD), checking non-normal results (excluding PGD), analysis of normal results. 

We will also require somewhere to record who created and checked a runsheet - maybe this can be set up in a prompt during runsheet creation. We will need to have a chart for runsheet creation and checks as well.

A search by date query for the above tasks will also be helpful.

Sorry to be pushy but this is rather urgent as we need to complete all our audits for ISO by end of March. 

Please come and speak to me, Adele or Charlotte for more details.

Ta very much,
Sarah

**Comment by schuiie** [comment]
Aloha! 

Please can this be done by end of February so that we have enough time to complete our competency forms. 

Ta ta, 
Sarah

**Comment by woook** [comment]
Checking normal results (excluding PGD), checking non-normal results (excluding PGD), analysis of normal results and analysis of general referral normals (in lieu of reporting) done.

Runsheet creation & checking postponed until the general automation of runsheeting is picked up.
