### ISSUE TITLE
WES - checking exome status email

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#69]
Hi guys,

When using the 'Check exome status' function and opening the case to check panels and comments there are a button with 'Email Duty Scientist' that should be changer to 'Email WES Team' with email wes@viapath.co.uk attached.

Cheers, /Matt

**Comment by aledj2** [comment]
old email address found on:
87010 ExomePatient_CustomMsgBox
s87018_ExomeStatusPopup
87010 ExomePatients
87016_Exome_Internal_ApprovalForm
87017 Exome_External_ApprovalForm

**Comment by MattiasJanssonviapath** [comment]
Looks like all those should be WES@viapath.co.uk 
Cheers, /Matt

**Comment by andyb3** [comment]
Done
