### ISSUE TITLE
UCSC Array Tracks

### ISSUE THREAD

**Issue by adelecorrigan** [moka-guys/helpdesk#7]
Please can we transfer responsibility for managing UCSC tracks to the array DS?
Starting with the removal of the filtered design probe coverage track.

Thanks!

**Comment by woook** [comment]
A new UCSC account has been created for devdisorder using the devdisorders@gmail.com email address and so the array DS will be able to administer it.

The new url for UCSC should be used by Moka (a new issue will be raised)
