### ISSUE TITLE
Modification to Bed file Pan1456

### ISSUE THREAD

**Issue by rachaelmein** [moka-guys/helpdesk#71]
BED file for Pan1456 for is missing 2 exons of COL4A5.

Genomic coordinates for COL4A5 Exons 42 and 43 are:

COL4A5 (LRG_232t2):
Exon 42   
start c.3791    NC_000023.10:g.107913458G>A 
finish c.3799   NC_000023.10:g.107913466G>A 

Exon 43  
start c.3800 NC_000023.10:g.107917975G>A
finish c.3808  NC_000023.10:g.107917983G>A

Michael has spoken to Andy about this.  
Please can you also check if these 2 exons need to be added to the coverage BED file (Pan1158).

**Comment by aledj2** [comment]
Hi Rachael, 

The CNV bedfile aspect of this issue is being done in issue (#75).

COL4A5 isn't in Pan1158 (NGSEQ2) at all, however it is in NGSEQ1 (Pan1157) - this was remade recently (pan1965) with these extra exons.

NGSEQ1 samples will now need Pan1965 in the sample name. Any idea when samples are likely to be run with this panel?

Aled

**Comment by rachaelmein** [comment]
Hi Aled

I am not sure what you mean by “COL4A5 isn't in Pan1158 (NGSEQ2) at all, however it is in NGSEQ1 (Pan1157) - this was remade recently (pan1965) with these extra exons”  Have I  entered something wrong on Moka that makes you think COL4A5 should be in NGSEQ2??

See P:\DNA LAB\Current\NGS worksheets\Ingenuity Panel Lists\ Custom PanelCodes for what we should now have as active panels

All the validation samples have already been run so will have the wrong Pan number in the sample name.  They are on NGS171B, NGS175B and NGS203A

Rachael

**Comment by aledj2** [comment]
Hi Rachael, 

Sorry I wasn't very clear, 
re "BED file for Pan1456 for is missing 2 exons of COL4A5."
Pan1456 is NGSEQ2 CNV bedfile (+/-50bp). I think you were asking to include the missing COL4A5 exons into NGSEQ2 bed files, however COL4A5 isn't listed in NGSEQ2. 

COL4A5 is in NGSEQ1 however, and the missing exons have been added to these bed files (Pan1965/Pan1971).


re "Please can you also check if these 2 exons need to be added to the coverage BED file (Pan1158)."

Did you mean to check if the extra COL4A5 exons were included in the NGSEQ1 +/-10bp bedfile (Pan1965)?

Thanks,
Aled

**Comment by rachaelmein** [comment]
Hi Aled

I understand what I have done now.  Sorry I quoted the wrong Pan number on the github issue.  It should have said “modification to Pan1455”.  The missing COL4A5 exons have nothing to do with NGSEQ2 Pan1456 and Pan1158. I have also put the wrong pan number in my question  "Please can you also check if these 2 exons need to be added to the coverage BED file (Pan1158)."  This should have been Pan1157 however this has been superseded now as we have made new pan number for NGSEQ1 Variant (Pan1965) to ensure missing exons are in CNV analysis Bed file and in the coverage bed file.

So sorry for the confusion, too many different panel numbers!

Rachael

**Comment by aledj2** [comment]
No problem Rachael,


I've re-made Pan1971. Hopefully this will be code reviewed and sent to you for review in the next few days.


Pan1965 does contain the extra exons.


I'm going to close this issue as the creation of NGSEQ1, 2 and 3 CNV bed files is covered in #75.


Aled

Aled Jones
Clinical Bioinformatician
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: aledjones@nhs.net
________________________________
