### ISSUE TITLE
Moka doesn't work

### ISSUE THREAD

**Issue by IrinaStasevich** [moka-guys/helpdesk#73]
Hi,

The Moka database on my computer stopped working. When i try to open in I am getting a message:
Unrecognised database format "H:\Moka\master.mdb", please also see the attachment
Could you please help me to fix it.

Many thanks,
irina
[unrec_moka.docx](https://github.com/moka-guys/helpdesk/files/1681872/unrec_moka.docx)

**Comment by andyb3** [comment]
Resolved
