### ISSUE TITLE
WES - COverage report error

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [moka-guys/helpdesk#74]
Hi guys,

Got an error report when generating coverage report for TestID1335, Pan1662
NGS146C_24_96684_AP_WES10_S10_R1_001.refined

Cheers, /Matt

**Comment by aledj2** [comment]
Can you try again now please Matt.
Ta

**Comment by MattiasJanssonviapath** [comment]
Hi Aled,

Still same error.

Cheers, /Matt

**Comment by aledj2** [comment]
do you mean NGS test id 373 rather than 1335?

**Comment by MattiasJanssonviapath** [comment]
Nope, TestID1335. It's a re-run.

**Comment by aledj2** [comment]
Sorry Matt, What run was it re-run on?

It's down as being on batch 23 which I don't think we've seen yet. Does it have the same DNA number?

Aled

Aled Jones
Clinical Bioinformatician
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: aledjones@nhs.net
________________________________

**Comment by MattiasJanssonviapath** [comment]
Sorry, poor choice of words, it's a re-analysis of old data. It's on WES0, not 23. 
This is where the data is: NGS146C_24_96684_AP_WES10_S10_R1_001
