### ISSUE TITLE
Bespoke coverage report NGS Test ID 766

### ISSUE THREAD

**Issue by RachaelIrwinViapath** [moka-guys/helpdesk#76]
Hi, please can we have a bespoke coverage report for WES case NGS Test ID 766 (DNA 181417), from WES17. This case had a C4 variant identified in the Primary panel so we have agreed with the clinician that analysis of the Secondary panel is not required - therefore we need a coverage report with only the Primary panel (Pan608) and not including the Secondary (Pan1143). Thank you! Rachael.

**Comment by aledj2** [comment]
Done,
It's in the usual place. 
Please check!
Thanks,
Aled

**Comment by RachaelIrwinViapath** [comment]
Great, thanks Aled! Have checked it - all good.

Cheers,
Rachael

________________________________
