### ISSUE TITLE
VCF uploads

### ISSUE THREAD

**Issue by laurenpitt** [moka-guys/helpdesk#79]
Hi, I cannot upload my VCF's onto moka because a message tells me there are multiple VCFs with similar details. Is it possible to delete the file I don't need or will this mess it up?
Thanks

**Comment by andyb3** [comment]
Hi Lauren. Yes if you remove the file you don't need from the folder then the upload should work.

**Comment by andyb3** [comment]
(I'll close this issue for now but feel free to re-open if you continue to have problems)
