### ISSUE TITLE
WES coverage report

### ISSUE THREAD

**Issue by hkuoppamaa** [moka-guys/helpdesk#8]
Could coverage report be generated for PRU 406176:01, Test ID 716 for Pan1019 please? I'm currently unable to generate them myself.
Thanks!

**Comment by aledj2** [comment]
Hi Heidi,

We've updated Moka so hopefully you can now generate the reports - can you have a go please.


However through Moka you can still only generate coverage for all the panels assigned to the test so if you only need a subset of panels let me know and I'll sort it.


Ta


Aled

Aled Jones
Clinical Bioinformatician
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: aledjones@nhs.net
________________________________

**Comment by hkuoppamaa** [comment]
Hi Aled,

It still doesn't work for me. I just closed it down and tried again (so is all up to date) and I still get the same error message :/

Cheers,
Heidi

**Comment by aledj2** [comment]
done. 
Ta 
Aled
