### ISSUE TITLE
WES - Moka Primer database

### ISSUE THREAD

**Issue by JodieYates** [moka-guys/helpdesk#81]
Hi,

I forgot to remove a failed primer from the PHIGIS output file before importing into MOKA (fragment ID 520; NMD_NEB_Ex155). This primer has now been re-designed manually. I haven't ordered the redesigned primer yet but hope to do so tomorrow (Friday) along with the rest of the primers designed by the script.

The email mentioned failing the current entry so the newly designed primers can be imported. Can you please do whatever you need to in order to fix my error! 

If you need anymore info let me know.

Many thanks 

jodie :)

**Comment by aledj2** [comment]
ok. this has been set to failed and I've put a comment in.
Hopefully this should now be ok (and not show up in the to be ordered list).

Feel free to re-open if this hasn't fixed it
