### ISSUE TITLE
NGS sample required

### ISSUE THREAD

**Issue by helenstorey** [moka-guys/helpdesk#86]
Hi
I was just wondering if I could have a sample from NGS203 put back on ingenuity - it's sample NGS203A_20_179418_EP_F_ALP_Pan1451_S20_R1_001

Many thanks
Helen

**Comment by andyb3** [comment]
Hi. Have just resubmitted it so hopefully should appear soon. Thanks, Andy.

**Comment by helenstorey** [comment]
Thanks!
