### ISSUE TITLE
Swift ONC58

### ISSUE THREAD

**Issue by mneat** [moka-guys/helpdesk#89]
ONC58 has stalled again – no varscan vcf’s or coverage reports

**Comment by aledj2** [comment]
Hi Michael, sorry about this. It's been restarted. Have made a fix,it just needs validating

**Comment by aledj2** [comment]
The workflow is complete, please let us know if there are any further issues with this run.

**Comment by woook** [comment]
Hi Aled

Could you find out when the next oncology run is so we have a date to aim for to pushout the fix?

Thanks,

Wook

**Comment by aledj2** [comment]
will be going through Nexus Thursday morning.
