### ISSUE TITLE
Pan2022/Pan1974 CMCMD

### ISSUE THREAD

**Issue by rachaelmein** [moka-guys/helpdesk#94]
I would like to use a different transcript for INPP5K gene for coverage and RPKM.  I also wish to add in the promoter for MTM1 (chrX:149737047-149737112)  into RPKM.  

New Pan numbers have been created in Moka.  Pan2022 replaces Pan1464 for coverage and Pan1974 replaces Pan1471 for RPKM.  The next batch of CMCMD will be set up on 16th March so I need to know by then if this has been done so to enter new Pan number in sample sheet.

Thanks
Rachael

**Comment by aledj2** [comment]
Have requested bed file requirements form to be completed

**Comment by AmyAmelia** [comment]
Please name the samples with the latest Moka pan number (Pan2022). Please note that these sample will not be processed until the bed file requirements form is completed.

**Comment by aledj2** [comment]
[Pan2022 Request for bed file creation.docx](https://github.com/moka-guys/helpdesk/files/1923391/Pan2022.Request.for.bed.file.creation.docx)
[Pan1974 Request for bed file creation.docx](https://github.com/moka-guys/helpdesk/files/1923392/Pan1974.Request.for.bed.file.creation.docx)

**Comment by aledj2** [comment]
These bed files have been created but as far as I know samples haven't been processed to test the new regions - is this required?
Further work is required before these bedfiles are used by the automated scripts (and samples renamed to use these bed files) (woook/automate_demultiplex#206)
