### ISSUE TITLE
Update Patient Details in Moka (to update Moka after GeneWorks change) not working 

### ISSUE THREAD

**Issue by CharlotteLee1** [moka-guys/helpdesk#97]
Update Patient Details in Moka (to update Moka after GeneWorks change) not working, as initials cannot be typed into or selected from the drop down menu in the "UpdatedBy" box. Not working for both AC and CVL.

**Comment by AmyAmelia** [comment]
Form 4751 - drop down box not responding

**Comment by AmyAmelia** [comment]
Should work now.
