### ISSUE TITLE
Additional change following paperless array analysis

### ISSUE THREAD

**Issue by ClaRomano** [moka-guys/helpdesk#99]
Would it be possible to view the hyb ID of family members of the hyb partner in Moka array result page? This would be useful when doing prenatal analysis as, when prenatals are hyb'd against inheritances, we need to take screenshots of regions of interests >400Kb. Thanks

**Comment by andyb3** [comment]
Tackle at same time as https://github.com/woook/moka-fe/issues/477

**Comment by andyb3** [comment]
HybIDs not displayed

**Comment by aledj2** [comment]
Hi Claudia, 
Sorry, when you have a second could you come and show me what you'd like to be displayed and where.
Ta
Aled

**Comment by aledj2** [comment]
This should now be in Moka. ta
